### ISSUE TITLE
package dirmngr missing (importing gpg-key for mariadb repo)

### ISSUE THREAD

**Issue by FalzoMAD** [hestiacp/hestiacp#68] opened 2018-11-28 19:05 UTC
running installer on debian stretch tries to add mariadb repo (ams DO) and gpg-key which fails:

```
Upgrade System using apt-get...
W: GPG-Fehler: http://ams2.mirrors.digitalocean.com/mariadb/repo/10.3/debian stretch InRelease: Die folgenden Signaturen konnten nicht überprüft werden, weil ihr öffentlicher Schlüssel nicht verfügbar ist: NO_PUBKEY F1656F24C74CD1D8
W: The repository 'http://ams2.mirrors.digitalocean.com/mariadb/repo/10.3/debian stretch InRelease' is not signed.
```

cause for this is the missing 'dirmngr' package:

```
# apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 0xF1656F24C74CD1D8
Executing: /tmp/apt-key-gpghome.91Xcxd0wMP/gpg.1.sh --recv-keys --keyserver keyserver.ubuntu.com 0xF1656F24C74CD1D8
gpg: failed to start the dirmngr '/usr/bin/dirmngr': Datei oder Verzeichnis nicht gefunden
gpg: connecting dirmngr at '/tmp/apt-key-gpghome.91Xcxd0wMP/S.dirmngr' failed: Datei oder Verzeichnis nicht gefunden
gpg: keyserver receive failed: Kein Dirmngr
```

installing the missing package via 'apt install dirmngr' fixes that problem and the installer runs through.

**Comment by ScIT-Raphael** [comment] 2018-11-29 07:35
Hi @FalzoMAD 

Thanks for your issue report, the problem is fixed with the following commit: https://github.com/hestiacp/hestiacp/commit/c4b1e243834975e3e8881939445f4890b8446142

We will check now, if dirmngr is installed by default and install it if not.

**Closed as completed by ScIT-Raphael** 2018-11-29 07:35 UTC
