### ISSUE TITLE
Email server with standard roundcube . Emails send but the person never receives them

### ISSUE THREAD

**Issue by mylesgoose** [hestiacp/hestiacp#1257] opened 2020-10-08 03:06 UTC
Hello. I have followed the instructions and have Hestiacp working on my server and can install websites and is quite good. However there is an email server included in this package round cube. Yet when I try to use it the round cube software says that is has sent email but we never receive the emails. or if try to send emails to the test email created, I do not receive them. and I receive no error messages from either email account. 

I tried to add the following settings to cloud dns from this website instructions, https://forum.hestiacp.com/t/email-with-cloudflare/1125/2

Create an A record Name mail and point it to your server ip

Create an A record Name webmail and point it to your server ip

MX record point Name domain.com and point it to mail.domain.com

TXT record with name domain.com and value

“v=spf1 a mx ip4:serverip ~all”

yet its does not work still. does this phrase have to say replace serverip with our ip address? is this my issue i tried replacing that and still no luck. 

Would someone be so kind as to walk me through the process of setting up the email server for my website using this roundcube. and specifically what settings i have to add to cloud dns or simply the process from start to finish. I cannot find any tutorials to follow to resolve this email sending issue.

 So far I have tried rolling a cube down the hill and hoping the edges shave off enough to become round so it will roll the emails into my server but that has not worked. 

Is there a guide somewhere to fix this issue? 

Also I remember setting up google gsuite a while ago to facilitate sending emails for my domain but I did not put a code in somewhere and the emails all got marked as spam because google did not have permission to send from my domain with a long key. it was years ago I did this and I am wondering is there the same issue with this round cube to fully secure it so that emails are not rejected as spam. 

any advice is appreciated as this is last step until our website is working well. with this new system

**Comment by mylesgoose** [comment] 2020-10-08 05:54
I open up ports ingress in google server and now it can receive emails from a Gmail account but not and iCloud account. and it still cannot send to any

**Comment by ScIT-Raphael** [comment] 2020-10-08 06:12
First thing I would check is the exim mainlog, to verify if the mail communication is working properly. Also this isnt a reproducable issue which we can fix in any way, so I'll close this for now. Please consider to switch over to https://forum.hestiacp.com or our Discord group, which would be the place for your request.

**Closed as completed by ScIT-Raphael** 2020-10-08 06:12 UTC

**Comment by mylesgoose** [comment] 2020-10-08 06:20
> First thing I would check is the exim mainlog, to verify if the mail communication is working properly. Also this isn't a reproducible issue which we can fix in any way, so I'll close this for now. Please consider to switch over to https://forum.hestiacp.com or our Discord group, which would be the place for your request.

So far i have reproduced the issue on two servers and a friend has also reproduced the issue on his server.

are you able to explain what you do to make the email work. i setup in a google cloud platform vm server running linux ubuntu 20.04. where about do i find this log you speak of? i have opened all the ports in the firewall on google platform.

**Comment by ScIT-Raphael** [comment] 2020-10-08 06:29
The mailserver mostly works out of the box, the only thing you've to do is finetuning like set reverse dns records for your static ip and maybe dkim and spf records. After that, you always get a 10 out of 10 on mailtester.com.

The exim mainlog is in /var/log/exim/mainlog, it will give you more informations about if your emial is even transmitted to the remote mail server. Marked as spam is also another, common issue, there was already a discussion about it in our discord group: https://discordapp.com/channels/737721354937303161/738055454285889597/761938451113050164

**Comment by mylesgoose** [comment] 2020-10-08 06:40
okay i spoke to cloudns and they said my settings are okay in there. would you please explain specifically what settings I need to adjust to get it to work. I am not a professional with these things. normally I can follow tutorials online and get things to work. but in this instance I cannot find a tutorial for setting up those setting you refer to. I have email servers working just fine in other systems. after setting the ip address correctly with the cloudns then the emails started to be received from specifically only gmail accounts but not icloud. and it still does not allow me to send to others even to myself. I tried a fresh install and same issue. my friends has a server in his basement next door and he installed there also and he has done many servers and he has same issue. does nto send at all on his one or receive. admittedly we are probably using the same cloudns settings. 
how can I get to the log files. is there some sort of instructions for setting up the email online I cannot find any. regards this system is jsut a test situation it is not a live site if you would like to check can give access to it.

**Comment by jaapmarcus** [comment] 2020-10-08 06:50
Sending email is not possible over port 25

https://cloud.google.com/compute/docs/tutorials/sending-mail

Receiving  email is strange there should be no reason Send the email and check the headers what is going wrong

**Comment by mylesgoose** [comment] 2020-10-08 06:52
i found that log file with you help above thanks. except the directory had  EXIM4 no exim one exisited.

the logs are numerous.
(110): connection times out h=alt4.gmail-smtp-in.l.google.com {ipaddress} :smtp timeout after initial connection.
 (-53): retry time not reached for any host for icloud.com
 (-53): retry time not reached for any host for gmail.com

**Comment by ScIT-Raphael** [comment] 2020-10-08 06:55
> (110): connection times out h=alt4.gmail-smtp-in.l.google.com {ipaddress} :smtp timeout after initial connection.

probaly exactly what @jaapmarcus wrote :).

**Comment by mylesgoose** [comment] 2020-10-08 07:03
I have a feeling your both correct in this analysis of the problem. becasue when i opened all the ports that is when the software round cube started receiving at least partially from one address gmail but not icloud. in my cloud.google firewall rules as it is a test server for me to learn i just opened up all the ports like this in the firewall.

webmail | Ingress | Apply to all | IP ranges: 0.0.0.0/0 | tcp:22,25,110,119,143,465,443,563,587,993,995,8083 | Allow | 1000 | default | Off
and also egress same.
so as you can see the port 25 is open in google firewall. in the tutorial you sent. they specifically state that we cant use port 25 because of abuse. so are you saying that this round cube is using port 25 and that is blocked even with the firewall open?
what would you recommend since i have already previously done the steps in that document above to do. do i need to change the port somehow that round cube used for emails. if so how is that achieved to create a new port to use in round cube and then I can open that port in googles firewall.

Thank you both for your help it is interesting to learn about this system.

**Comment by jaapmarcus** [comment] 2020-10-08 07:55
Exim is used for send email and normally port 25 is used for that and not Roundcube. 

Consider the use of a different VPS provider that allows traffic over port 25.

Also  retry time not reached for any host for icloud.com

Are you trying to download emails from the iCloud server?

Please try an different VPS provider for reciving email it should not be an issue..

**Comment by mylesgoose** [comment] 2020-10-08 08:05
Are you saying that this software is not compatible with google because they block port 25 which exim4 uses? so even if my port is open in google vps that it wont work? and your suggestion is to use a different vps which does not block port 25? I have allot of credit in google. So i would like to keep using that. credit and I would like to keep it all on same server. can I not change the port which exim uses? so this is a fault with this software and compatibility with google cloud? 
something like this?
https://petalhost.in/blog/change-default-smtp-port-exim-postfix/

actually i cant follow that instruction because i cant find the files to edit in the newer system. but surly we can do similar thing to this fix shown in this link to make this software compatible with google cloud. use port 26 or something

**Comment by jaapmarcus** [comment] 2020-10-08 08:49
If an provider decides to block port 25 for what ever reason we can't change that.

> Using standard email ports
> By default, Compute Engine allows outbound connections on all ports except port 25, which is blocked because of the risk of abuse. All other ports are open, including ports 587 and 465.
> Note: Port 25 is always blocked and can't be used, even through an SMTP relay using Google Workspace.

If you follow the page link the offer multiple options that you are able to try.  We don't know the solutions that suits you the best.... You can try what you want how ever we can't give support on everything...

We "from" Hestia at least consider users to be familiar with servers / and know the basic principles and at least able to do certain task...

Also please use: https://forum.hestiacp.com 

There are often more persons around over there...

**Comment by mylesgoose** [comment] 2020-10-08 08:58
I think that many ISP and servers block ports 25. from reading this. your advice has been great and I appreciate it thanks. you released a package which is not compatible with the most popular webserver. so in my oppinion this is best to fix in your release.
to change the port you should use SMTPLISTENEROPTIONS='-oX 26:587:10025 -oP /var/run/exim4/exim.pid' in file /etc/default/exim4 this should then make yours software compatible with any web server because if users know how to change the port or better yet in your config file you just use a port that is not blocked. because any user that installs your software on google cloud will have this issue. and perhaps waste 3 days trying to solve it.

**Comment by tudorr89** [comment] 2020-10-08 09:07
> I think that many ISP and servers block ports 25. from reading this. your advice has been great and I appreciate it thanks. you released a package which is not compatible with the most popular webserver. so in my oppinion this is best to fix in your release.
> to change the port you should use SMTPLISTENEROPTIONS='-oX 26:587:10025 -oP /var/run/exim4/exim.pid' in file /etc/default/exim4 this should then make yours software compatible with any web server because if users know how to change the port or better yet in your config file you just use a port that is not blocked. because any user that installs your software on google cloud will have this issue. and perhaps waste 3 days trying to solve it.

I don't mean to be rude here, but if you had some basic linux knowledge, you would be able to fix the problem yourself since you only need to change the port in exim. 

Furthermore, you are confusing email clients with email server software and more than that cloud infrastructure with web server software. 

There is nothing to fix other than your poor knowledge on the matter.

Cheers!

**Comment by ScIT-Raphael** [comment] 2020-10-08 09:10
> > I think that many ISP and servers block ports 25. from reading this. your advice has been great and I appreciate it thanks. you released a package which is not compatible with the most popular webserver. so in my oppinion this is best to fix in your release.
> > to change the port you should use SMTPLISTENEROPTIONS='-oX 26:587:10025 -oP /var/run/exim4/exim.pid' in file /etc/default/exim4 this should then make yours software compatible with any web server because if users know how to change the port or better yet in your config file you just use a port that is not blocked. because any user that installs your software on google cloud will have this issue. and perhaps waste 3 days trying to solve it.
> 
> I don't mean to be rude here, but if you had some basic linux knowledge, you would be able to fix the problem yourself since you only need to change the port in exim.
> 
> Furthermore, you are confusing email sending client with email servers and more than that cloud infrastructure with web server software.
> 
> There is nothing to fix other than your poor knowledge on the matter.
> 
> Cheers!

![image](https://i.kym-cdn.com/photos/images/original/000/566/702/3f2.jpeg)

**Comment by mylesgoose** [comment] 2020-10-08 09:24
> > I think that many ISP and servers block ports 25. from reading this. your advice has been great and I appreciate it thanks. you released a package which is not compatible with the most popular webserver. so in my oppinion this is best to fix in your release.
> > to change the port you should use SMTPLISTENEROPTIONS='-oX 26:587:10025 -oP /var/run/exim4/exim.pid' in file /etc/default/exim4 this should then make yours software compatible with any web server because if users know how to change the port or better yet in your config file you just use a port that is not blocked. because any user that installs your software on google cloud will have this issue. and perhaps waste 3 days trying to solve it.
> 
> I don't mean to be rude here, but if you had some basic linux knowledge, you would be able to fix the problem yourself since you only need to change the port in exim.
> 
> Furthermore, you are confusing email clients with email server software and more than that cloud infrastructure with web server software.
> 
> There is nothing to fix other than your poor knowledge on the matter.
> 
> Cheers!

I don't pretend to be an expert as i said i am learning about setting up this email system, i do have a degree in computer science. you cant understand every single thing of every persons software. even you guys supposed to create it didn't understand this. and yet all three of you could not provide a solution and I solved the issue myself by editing that file. you even quoted my post with the instructions on how I did it and then have the check to say I should know how to do that. when i just explained how to do it. so what are you talking about. it was you guys that could not solve the simple issue with your software. a two sentence instruction to edit a file with a new port address would have sufficed. instead you let me try find redundant files for new system and change hosting providers. i don't use exim for my emails i normally use gsuite and send from my domain from there. this is new to me. 

Next time you need me to figure out the flaws with your software while you sit there and pretend to be intelligent offering solutions like changing providers. instead of editing a line of code like I have suggested to make your system compatible with the most popular server just let me know. how long did it take me to find that solution to edit the code which the default port was? why not just say that in first place if you knew. it is very obvious that a port was blocked by firewall hence why i had already unblocked all the ports still didnt work. when you knew that google blocks 25 why not just  say to edit one line of code to change port. in the absence of any assistance to change the port i had to waste over an hour searching for the config file to do such a thing. your solution is our service uses port 25 so problem is your end change providers. this like getting a new bike because the tire is flat. Problem is that port 25 and others are blocked by many vps. and isp. so provide a solution to change port. not every person is going know what configuration file to change. it has taken me an hour to find the specific file in new exim4 to edit. and now when someone searches for an answer to this same question with fault with this setup. they will haev a solution.

**Comment by ScIT-Raphael** [comment] 2020-10-08 09:43
@mylesgoose Exim is not "our" software, it is a part of hestia which we preconfigure - this doesnt mean that it runs everytime out of the box. Also your change does probaly stop incoming mail communication, because you removed listening on port 25. As I've already written, your request would be placed better on our forum or discord channel - on the forum you would also see the following disclaimer: https://forum.hestiacp.com/t/please-read-this-before-you-start/383

As @tudorr89 also wrote, it isnt mean to be offensive, everyone needs to start somewhere - but we can't provide support due to lack of knowledge - we could create step by step documentation for everything, but this is not the idea behind hestia.

Also there are only a few vps provider that are blocking port 25, but as @tudorr89 already written, you mix client and server sided communication. Clients usualy use tls/ssl and port 587 (or 465) for communication, server to server communication (transmitting mails) are mostly communicating over port 25 (but also tls/ssl).

tl;tr: I would suggest to verify, that incoming and outgoing mail communication are working properly - all other points have been answered.

**Comment by mylesgoose** [comment] 2020-10-08 10:24
I don't mean to be offensive but your mother is ugly. By saying I don't mean to be offensive and saying something offensive does not make it not offensive. All I am saying is that if you are aware that Hestia will not work on google servers without modifications. then it is a good idea to mention this or a solution to running on it in the documentation provided with it.  it is a replicatable issue with this "software bundle" that we have now determined, my next door computer friend he has a server in his basement and his server does the same thing when he installs it. My advice is during the install questions while running the installer and installing exim4 and roundcube to ask a question and user gives a response. does your server block ports 25 for email like google?. if yes what port would you like and you rsimpel script changes that port. else use port 25. Done. Or have a simple one page explanation on how to change the ports in exim4 after setup to make compatible with all servers and then Hestia is truly an out of the box solution. then nobody will have that issue again. its not ideal for us to go and edit config files to get your installer to function after run because then when you distribute updates etc what then they system might break with anew config file downladed. etc. this is not an intuitive issue to solve. One expects it to be able to run normally.

 There is no documents online about exim4 and files to edit. no commands we should know other than what is listed in the file itself, there is documents about exim but old versions with different file paths and file names. tudor89 thinks I should just know these out of the box like some wizard..  You have chosen to specifically integrate this software into your installer, not everyone is and expert with this exim4 and roundcube. and as someone newly installing this  will find all online tutorials are for older versions with completely different file paths. or when you try to search for hestia brings up old vestia version examples or some goddess. if you have step by step documentation for setup of your software then many more people can use it if they have an issue and have followed instructions clearly then they know it is issue with their setup.. and it would have more people wanting to help develop it. and community larger. Yes I have dyslexia and mix up words sometimes sure.  regarding your link yes i am aware of how to manage server i have been doing that since I was 18 and i am 37 now it was much harder back them, now all automated mainly. . Each of my business I have setup my own websites and hosted them. I decided to learn your system to see if it is smarter. Between me and my friend we can install your system run any website we want and have tried prestashop and wordpress etc and its all working very well. Just the email system does not work on home server or google server. it makes sense now why it did not work on google. I could not understand why it not working because all of our setting s are correct.  yet will look at the home server one tomorrow. I am not entirely confident that this email client is the best one to use anyway because i cant see how to properly encrypt the mail. like protonmail does. the object here was to test your system and then deploy it on our home system. but I feel like I'm learning now how to install an older version when the times have moved to newer email systems. with full encryption of the email perhaps i still need to understand why this client does not offer that. Since I have 500$ of free google use I like to deploy on there and test before using it on home servers. before using on my real websites. First install it then try to hack or see if it breaks how reliable using a more reliable server. If it cant be broken then let my business use it.

**Comment by ScIT-Raphael** [comment] 2020-10-08 10:35
Infact I don't have a lot of time, just a short demostration, how I try to resolve such issues:

1. Google your issue, in your case "exim google vps", find the following site (pos. 1): https://groups.google.com/g/gce-discussion/c/D-5aQHlH3OU
2. Second google round, "how to add additional port to exim", find the following site (pos. 2 - filepath is outdated but leads you to the right point -> /etc/exim4/exim4.conf.template): http://blog.serverbuddies.com/configure-exim-to-listen-on-additional-ports/
3. Issue resolved.

Also on first point, you'll find an important information: "The traffic on ports 25, 465 and 587 is blocked for the outbound requests and not inbound which is why you are able to receive emails and not send on these ports.", so incoming port 25 is still a need to leave in your exim configuration.

There is no need to documentate such a thing or implement it even to the installer, because this part is "basic knowledge" or can be found out within approx 5 minutes using google (as proofed above).

Infact the issue isnt a issue to resolve for hestia and further discussion isnt needed, I gonna lock this thread now.
