### ISSUE TITLE
All PHP-FPM versions installed even if not mentioned in installer

### ISSUE THREAD

**Issue by mehargags** [hestiacp/hestiacp#231] opened 2019-03-26 09:05 UTC
Ok,
So I tested on many provider's VPS, on Debian  and on Ubuntu.
I wget hst-install-ubuntu.sh and then edit it manually 
```
multiphp_v=("7.0" "7.1")
fpm_v="7.1"

```
Because I don't want 5.6 or 7.3 right now.
Still, when I install hestiacp all PHP-FPM versions installed even if not mentioned in the installer. Can this be fixed please ?

Thanks

**Comment by ScIT-Raphael** [comment] 2019-03-26 09:54
Just tested on a Ubuntu 18.04 LTS hosted on hetzner (using their cloud service). As you wrote, I edited the file to install 7.0 and 7.1 only. Then I started the process with the following command:
`bash hst-install-ubuntu.sh --multiphp yes --apache no --phpfpm yes`

After checking the software output it shows that the following packages should be installed:
`apparmor-utils awstats bc bind9 bsdmainutils bsdutils clamav-daemon cron curl dnsutils dovecot-imapd dovecot-pop3d e2fslibs e2fsprogs exim4 exim4-daemon-heavy expect fail2ban flex ftp git idn imagemagick lsof mc mariadb-client mariadb-common mariadb-server nginx ntpdate php php-cgi php-common php-curl phpmyadmin php-mysql quota roundcube-core roundcube-mysql roundcube-plugins rrdtool rssh spamassassin sudo hestia hestia-nginx hestia-php vim-common vsftpd webalizer whois zip php7.0-mbstring php7.0-bcmath php7.0-cli php7.0-curl php7.0-fpm php7.0-gd php7.0-intl php7.0-mysql php7.0-soap php7.0-xml php7.0-zip php7.0-mbstring php7.0-json php7.0-bz2 php7.0-pspell php7.0-mcrypt php7.1-mbstring php7.1-bcmath php7.1-cli php7.1-curl php7.1-fpm php7.1-gd php7.1-intl php7.1-mysql php7.1-soap php7.1-xml php7.1-zip php7.1-mbstring php7.1-json php7.1-bz2 php7.1-pspell php7.1-mcrypt`

Until now, I don't see any other php versions - also I checked the output of apt-get install:
`   apache2-bin apparmor-utils awstats bind9 bind9utils clamav-base clamav-daemon clamav-freshclam
  dbconfig-common dbconfig-mysql dovecot-core dovecot-imapd dovecot-pop3d e2fslibs exim4 exim4-base
  exim4-config exim4-daemon-heavy expect fail2ban flex fontconfig fontconfig-config fonts-dejavu-core
  galera-3 hestia hestia-nginx hestia-php hicolor-icon-theme idn imagemagick imagemagick-6-common
  imagemagick-6.q16 libaio1 libapache2-mod-php7.3 libapr1 libaprutil1 libaprutil1-dbd-sqlite3
  libaprutil1-ldap libaspell15 libcairo2 libclamav7 libcrypt-openssl-bignum-perl
  libcrypt-openssl-rsa-perl libdatrie1 libdbi-perl libdbi1 libdigest-hmac-perl libexttextcat-2.0-0
  libexttextcat-data libfftw3-double3 libfontconfig1 libgd3 libgomp1 libgraphite2-3 libharfbuzz0b
  libhtml-parser-perl libhtml-tagset-perl libhttp-date-perl libio-socket-inet6-perl libio-socket-ssl-perl
  libjbig0 libjpeg-turbo8 libjpeg8 libjs-jquery libjs-sphinxdoc libjs-underscore liblcms2-2 libllvm3.9
  liblqr-1-0 libltdl7 liblua5.2-0 libmagickcore-6.q16-3 libmagickwand-6.q16-3 libmail-dkim-perl
  libmailtools-perl libmcrypt4 libmysqlclient20 libnet-dns-perl libnet-ip-perl libnet-smtp-ssl-perl
  libnet-ssleay-perl libnetaddr-ip-perl libnl-3-200 libnl-genl-3-200 libpango-1.0-0 libpangocairo-1.0-0
  libpangoft2-1.0-0 libpcre2-8-0 libpixman-1-0 libpq5 librrd8 libsocket6-perl libsodium23 libssh2-1
  libsys-hostname-long-perl libtcl8.6 libtfm1 libthai-data libthai0 libtiff5 libtimedate-perl libtirpc1
  liburi-perl libwebp6 libxcb-render0 libxcb-shm0 libxpm4 libxrender1 libzip4 m4 mariadb-client
  mariadb-client-10.3 mariadb-client-core-10.3 mariadb-common mariadb-server mariadb-server-10.3
  mariadb-server-core-10.3 mc mc-data mysql-common nginx ntpdate perl-openssl-defaults php php-auth-sasl
  php-cgi php-common php-curl php-mail-mime php-mysql php-net-sieve php-net-smtp php-net-socket php-pear
  php-php-gettext php-phpseclib php7.0-bcmath php7.0-bz2 php7.0-cli php7.0-common php7.0-curl php7.0-fpm
  php7.0-gd php7.0-intl php7.0-json php7.0-mbstring php7.0-mcrypt php7.0-mysql php7.0-opcache
  php7.0-pspell php7.0-readline php7.0-soap php7.0-xml php7.0-zip php7.1-bcmath php7.1-bz2 php7.1-cli
  php7.1-common php7.1-curl php7.1-fpm php7.1-gd php7.1-intl php7.1-json php7.1-mbstring php7.1-mcrypt
  php7.1-mysql php7.1-opcache php7.1-pspell php7.1-readline php7.1-soap php7.1-xml php7.1-zip php7.3
  php7.3-cgi php7.3-cli php7.3-common php7.3-curl php7.3-json php7.3-mysql php7.3-opcache php7.3-readline
  phpmyadmin python3-apparmor python3-libapparmor python3-ply quota roundcube-core roundcube-mysql
  roundcube-plugins rrdtool rssh socat spamassassin ssl-cert tcl-expect vsftpd webalizer whois zip
`

There is php7.3 set, because of the packages `php php-auth-sasl php-cgi php-common php-curl php-mail-mime php-mysql php-net-sieve php-net-smtp php-net-socket php-pear php-php-gettext php-phpseclib` - i will do a exclude a rework of it in a next commit. But I still not see any other php-fpm versions!

```
root@web02:~# ls -l /etc/init.d/php*
-rwxr-xr-x 1 root root 4793 Mar  8 10:49 /etc/init.d/php7.0-fpm
-rwxr-xr-x 1 root root 4793 Mar  7 21:02 /etc/init.d/php7.1-fpm
```

As already wrote, the php7.3 package will be installed, but not the php fpm version. I can't reproduce your issue - because of that I will close this issue for now. Please feel free to reopen it or create a new one.

**Closed as completed by ScIT-Raphael** 2019-03-26 09:54 UTC
Labels: installer

**Comment by mehargags** [comment] 2019-03-26 21:29
Ok in my new tests... I see that it responds correctly to the chosen FPM Versions... however... the PHP CLI version is still always 7.3.   The default PHP FPM Flag set in the installer script should be honoured and the PHP CLI be set to the one set in default.

`update-alternatives --set php /usr/bin/php7.x`

**Comment by hestiacp** [comment] 2019-03-27 07:21
We just work at the docs under https://docs.hestiacp.com, I will place the update-alternatives command there - so everyone can set the required version on their own.

**Comment by ScIT-Raphael** [comment] 2019-03-27 07:22
We just work at the docs under https://docs.hestiacp.com, I will place the update-alternatives command there - so everyone can set the required version on their own.
