### ISSUE TITLE
[Bug] Punny code domains disapear

### ISSUE THREAD

**Issue by gotttlieb** [hestiacp/hestiacp#1618] opened 2021-02-11 17:50 UTC
**Describe the bug**
I was migrating from VestaCP, an one of my domains are Punny.
When it restores, seems that everything is runing normally, but no DB is restored, and when i go to domains, it have incremented the domain count, but no new domain is displayed.

**To Reproduce**
What steps did you take when the issue occured? 
1.-Get a VestaCP backup of a punny domain
2.-Try to restore it into hestia.
3.-Check that no domain is visible but number of domains is changed
( i have tryed to create a new one at hand, but same happens)

**Expected behavior**
The restore should go fine.

**Screenshots**
![image](https://user-images.githubusercontent.com/5620013/107676201-287cdd80-6c99-11eb-8d61-a0e96774dd69.png)

**Operating system:**
Debian 10.8

**Hestia Control Panel version:**
Fresh new install of 1.3.2

Thanks a lot for your time and help!

**Comment by jaapmarcus** [comment] 2021-02-23 20:58
I know there are many issues with Puny codes... Are you able to share a backup containing a puny code domain?

Please send an email to info@hestiacp.com or contact me on Discord (Same name)

**Comment by jaapmarcus** [comment] 2021-02-25 20:19
The issue is caused by in both Hestia / Vesta the "current" mechanism is just calling for issues 

For further imports:
https://github.com/hestiacp/hestiacp/pull/1640

Should stream line the issues

**Comment by jaapmarcus** [comment] 2021-04-22 11:26
Bugs should be fixed right now in 1.4

How ever due to the mess in VestaCP it still might cause issues

**Closed as completed by jaapmarcus** 2021-04-22 11:26 UTC
