### ISSUE TITLE
Letsencrypt renew doesnt works

### ISSUE THREAD

**Issue by arielesp** [hestiacp/hestiacp#1205] opened 2020-09-20 15:26 UTC
bad text

**Comment by ScIT-Raphael** [comment] 2020-09-20 16:47
First thing to say: The issue report template isnt decoration, please use it!

I see that you got a mix between error 2 and 3 which probaly arent related to a reproducable issue: https://docs.hestiacp.com/admin_docs/rest_api.html#return-codes

Aswell as you write that disabling and enabling the ssl certificate worked, it sounds like there was something wrong with the prior certificate.

As the problem is currently fixed for you due to the reregister of the lets encrypt certificate and the fact of missing issue report informations (os & version, hestia version, installation string...) I'm gonna close this issue report. Please feel free to open a new issue and fillout the template instead ctrl+a & del it :).

If you would like to do a deeper discussion, you can aswell use our forum or discord channel, which would give us the ability of a faster communication.

**Closed as completed by ScIT-Raphael** 2020-09-20 16:47 UTC

**Comment by jaapmarcus** [comment] 2020-09-21 06:51
Issue has been fixed 

1.2.4 has been released
