### ISSUE TITLE
failed to install on debain 9 and 10and ubuntu 18.4 16.04 and 20.04

### ISSUE THREAD

**Issue by liamgibbins** [hestiacp/hestiacp#1313] opened 2020-10-27 19:06 UTC
I tried to install on all OSes that I have available to me via my dedicated server provider and they all came up with the same error 
they are all clean installs and all updated and upgraded. 

**Error: apt-get install failed**

Here is the latest logfile (all are basically the same from all the tested OS.

Reading package lists...
Building dependency tree...
Reading state information...
ca-certificates is already the newest version (20190110~18.04.1).
curl is already the newest version (7.58.0-2ubuntu3.10).
dirmngr is already the newest version (2.2.4-1ubuntu1.3).
dirmngr set to manually installed.
gnupg is already the newest version (2.2.4-1ubuntu1.3).
wget is already the newest version (1.19.4-1ubuntu2.2).
The following additional packages will be installed:
  python3-software-properties unattended-upgrades
Suggested packages:
  bsd-mailx default-mta | mail-transport-agent needrestart
The following NEW packages will be installed:
  apt-transport-https python3-software-properties software-properties-common
  unattended-upgrades
0 upgraded, 4 newly installed, 0 to remove and 0 not upgraded.
Need to get 77.3 kB of archives.
After this operation, 914 kB of additional disk space will be used.
Get:1 http://asi-fs-n.contabo.net/ubuntu bionic-updates/universe amd64 apt-transport-https all 1.6.12ubuntu0.1 [1,692 B]
Get:2 http://asi-fs-n.contabo.net/ubuntu bionic-updates/main amd64 python3-software-properties all 0.96.24.32.14 [23.9 kB]
Get:3 http://asi-fs-n.contabo.net/ubuntu bionic-updates/main amd64 software-properties-common all 0.96.24.32.14 [10.1 kB]
Get:4 http://asi-fs-n.contabo.net/ubuntu bionic-updates/main amd64 unattended-upgrades all 1.1ubuntu1.18.04.14 [41.7 kB]
Preconfiguring packages ...
Fetched 77.3 kB in 0s (0 B/s)
Selecting previously unselected package apt-transport-https.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 61233 files and directories currently installed.)
Preparing to unpack .../apt-transport-https_1.6.12ubuntu0.1_all.deb ...
Unpacking apt-transport-https (1.6.12ubuntu0.1) ...
Selecting previously unselected package python3-software-properties.
Preparing to unpack .../python3-software-properties_0.96.24.32.14_all.deb ...
Unpacking python3-software-properties (0.96.24.32.14) ...
Selecting previously unselected package software-properties-common.
Preparing to unpack .../software-properties-common_0.96.24.32.14_all.deb ...
Unpacking software-properties-common (0.96.24.32.14) ...
Selecting previously unselected package unattended-upgrades.
Preparing to unpack .../unattended-upgrades_1.1ubuntu1.18.04.14_all.deb ...
Unpacking unattended-upgrades (1.1ubuntu1.18.04.14) ...
Setting up apt-transport-https (1.6.12ubuntu0.1) ...
Setting up unattended-upgrades (1.1ubuntu1.18.04.14) ...

Creating config file /etc/apt/apt.conf.d/50unattended-upgrades with new version
Created symlink /etc/systemd/system/multi-user.target.wants/unattended-upgrades.service â†’ /lib/systemd/system/unattended-upgrades.service.
Synchronizing state of unattended-upgrades.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable unattended-upgrades
Setting up python3-software-properties (0.96.24.32.14) ...
Setting up software-properties-common (0.96.24.32.14) ...
Processing triggers for systemd (237-3ubuntu10.42) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Processing triggers for dbus (1.12.2-1ubuntu1.2) ...
Processing triggers for ureadahead (0.100.0-21) ...
Reading package lists...
Building dependency tree...
Reading state information...
Calculating upgrade...
The following packages have been kept back:
  libargon2-0 libxml2
The following packages will be upgraded:
  libidn2-0 libpcre3 libssl1.1 openssl
4 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
Need to get 2,669 kB of archives.
After this operation, 176 kB of additional disk space will be used.
Get:1 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 libpcre3 amd64 2:8.44-2+ubuntu18.04.1+deb.sury.org+1 [239 kB]
Get:2 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 libidn2-0 amd64 2.3.0-1+ubuntu18.04.1+deb.sury.org+2 [69.1 kB]
Get:3 http://ppa.launchpad.net/ondrej/apache2/ubuntu bionic/main amd64 libssl1.1 amd64 1.1.1g-1+ubuntu18.04.1+deb.sury.org+1 [1,528 kB]
Get:4 http://ppa.launchpad.net/ondrej/apache2/ubuntu bionic/main amd64 openssl amd64 1.1.1g-1+ubuntu18.04.1+deb.sury.org+1 [832 kB]
Preconfiguring packages ...
Fetched 2,669 kB in 1s (2,426 kB/s)
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 61207 files and directories currently installed.)
Preparing to unpack .../libpcre3_2%3a8.44-2+ubuntu18.04.1+deb.sury.org+1_amd64.deb ...
Unpacking libpcre3:amd64 (2:8.44-2+ubuntu18.04.1+deb.sury.org+1) over (2:8.39-9) ...
Setting up libpcre3:amd64 (2:8.44-2+ubuntu18.04.1+deb.sury.org+1) ...
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 61207 files and directories currently installed.)
Preparing to unpack .../libidn2-0_2.3.0-1+ubuntu18.04.1+deb.sury.org+2_amd64.deb ...
Unpacking libidn2-0:amd64 (2.3.0-1+ubuntu18.04.1+deb.sury.org+2) over (2.0.4-1.1ubuntu0.2) ...
Setting up libidn2-0:amd64 (2.3.0-1+ubuntu18.04.1+deb.sury.org+2) ...
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 61230 files and directories currently installed.)
Preparing to unpack .../libssl1.1_1.1.1g-1+ubuntu18.04.1+deb.sury.org+1_amd64.deb ...
Unpacking libssl1.1:amd64 (1.1.1g-1+ubuntu18.04.1+deb.sury.org+1) over (1.1.1-1ubuntu2.1~18.04.6) ...
Preparing to unpack .../openssl_1.1.1g-1+ubuntu18.04.1+deb.sury.org+1_amd64.deb ...
Unpacking openssl (1.1.1g-1+ubuntu18.04.1+deb.sury.org+1) over (1.1.1-1ubuntu2.1~18.04.6) ...
Setting up libssl1.1:amd64 (1.1.1g-1+ubuntu18.04.1+deb.sury.org+1) ...
Setting up openssl (1.1.1g-1+ubuntu18.04.1+deb.sury.org+1) ...
Installing new version of config file /etc/ssl/openssl.cnf ...
Processing triggers for libc-bin (2.27-3ubuntu1.2) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...

**Comment by ScIT-Raphael** [comment] 2020-10-27 19:09
duplicate of #1312

**Closed as completed by ScIT-Raphael** 2020-10-27 19:09 UTC
