### ISSUE TITLE
Install MySQL instead of MariaDB

### ISSUE THREAD

**Issue by devilstars** [hestiacp/hestiacp#800] opened 2020-05-05 13:58 UTC
Hey!

Is it possible to install MySQL (5.7) instead of MariaDB?
The reason I ask - json field support.

Still in 2020-04 with MariaDB 10.5.2-beta, JSON is still just an alias for LONGTEXT, they don't have a proper JSON datatype - but MySQL has supported it since 2015-08

**Comment by ScIT-Raphael** [comment] 2020-05-05 14:10
Hi @devilstars 

officialy, this is not "supported". But I'm neary sure you can "just" remove mariadb, then install mysql 5.7.

Please let me know if it worked :). As the issue is answered, I'm going to close it, please let me know if you need any additional help!

**Closed as completed by ScIT-Raphael** 2020-05-05 14:10 UTC

**Comment by devilstars** [comment] 2020-06-23 07:18
> But I'm neary sure you can "just" remove mariadb, then install mysql 5.7.

Sadly it doesn't work. There must be an option in install script for that case.
