### ISSUE TITLE
Bug: Disabling ICMP needs OS reboot.

### ISSUE THREAD

**Issue by FarmanX** [hestiacp/hestiacp#201] opened 2019-03-12 08:20 UTC
### Brief issue description:
Firewall Issue (Needs complete server restart to apply the changes)

### Operating system distribution and release:
Ubuntu 18.04 LTS

### HestiaCP Version:
Type here (e.g. 0.9.8-27)

### What software is installed?
Apache, Nginx, PHP-FPM, Dovecot/Exim, MariaDB

**Comment by ScIT-Raphael** [comment] 2019-03-12 08:24
Can you please share more informations about your vps system or hoster you use? Usualy, the installation process triggers v-update-firewall, this will also be triggered after a reboot.

Could you maybe pleace do a test and run /usr/local/bin/hestia/v-update-firewall directly after install and check, if network connection comes back?

**Comment by FarmanX** [comment] 2019-03-12 09:13
It is installed on my ESXI Hypervisor 6.7. Now, I noticed that, it works for the other rules except for the ICMP echo requests. I tried to drop all ICMP packets it needs restart to take effect. Plus, this is another issue, sometimes when I navigate between the tabs of the CP, for example, from STATISTICS to SERVER it is very slow and takes almost 30 seconds to open. NOTE: my connection is stable.

**Comment by ScIT-Raphael** [comment] 2019-03-12 09:22
Hmm, just checked out on a hetzner vps: Installation went trough, network connectivity is ok. I also have a vmware esx system running for my company, dont have any issues.

Switchting between tabs should not be slow, this is just basic "php/html" code there - it looks like there is maybe some local issue (for example poor io) with your server?

**Comment by FarmanX** [comment] 2019-03-12 09:30
You tested the firewall to disable ICMP? Is it working fine for you? The ESXI is running multiple servers without any issues. It has a 10G connection and I am connected to the ESXI via 1G cable connection.
I think this is because I did not choose to install NAMED DNS service since I am planning to remotely manage the DNS Services

**Comment by ScIT-Raphael** [comment] 2019-03-12 10:00
Just checked it again: I can confirm, that disabling icmp needs a reboot. I'm not sure if this is related to iptables, because the rule will be removed correctly. If you do a iptables -L you will see, that icmp is removed from the input rules - so it should drop icmp request directly - will mark this as bug for a deeper check.

Can you share your install string you used? Also IO Performance has not much to do with bandwith of a network adapter. How does the system react on the server? Does a reboot goes fast? Is there any other performance issue?

**Comment by FarmanX** [comment] 2019-03-12 11:25
I think it is better to check it by urself. Since this is a test server, I can give you access to the server so that u can check the performance and maybe you will find the page loading issue. Just change between the tabs and you will notice. How can I send u the link to access the server?

**Comment by ScIT-Raphael** [comment] 2019-03-12 12:07
Please send a email to info@hestiacp.com.

**Comment by ScIT-Raphael** [comment] 2019-03-12 12:33
Can't find anything special: the tabs are loading with around 1-2 second delay, maybe caused due to latency.

**Comment by FarmanX** [comment] 2019-03-12 12:43
It is strange. :-\ 
Thanks anyways for the support. At least we found a bug. I will keep testing if it is like this for a long time I will let you know. Let's see if I can find other abnormalities.

**Comment by JOduMonT** [comment] 2019-04-15 13:48
@FarmanX 

### promiscuous
did you configure promiscuous mode anywhere in ESXi ?
your Hestia VM have an IPfix or dynamic ?

### gateway
what is your gateway ?
your gateway is outside of ESXi ?

### mtr
if you build another identical VM (Debian/Ubuntu) (same, specs, gateway and DNS) but without Hestia
could your launch `mtr --report google.com` on both and give us the result ?

**Comment by ScIT-Raphael** [comment] 2019-04-16 07:09
@jodumont I was able to reproduce the issue on any hestia test server - even if it was esx, physical or hetzner cloud.

**Comment by JOduMonT** [comment] 2019-06-11 08:03
I think it is more related to IPTables, network stack or even deeper than simply HestiaCP

When I look around of what I use: Proxmox, Debian, OVH, Hetzner, Scaleway, Exoscale ...
at one point, they all mention/recommend to do a reboot when you play with the firewall.

**Comment by ScIT-Raphael** [comment] 2019-06-11 08:04
Basicly, I think this is not a "critical" issue and we can stick on a documentation, that you need to reboot your system if you want to block icmp. I will close this issue for now.

**Closed as completed by ScIT-Raphael** 2019-06-11 08:04 UTC
Labels: bug, help needed
