### ISSUE TITLE
Testing HestiaCP 1.3.1 RC wont install.

### ISSUE THREAD

**Issue by Johnzapf** [hestiacp/hestiacp#1380] opened 2020-11-15 19:51 UTC
Not sure how to install zstd -  apt-get install didnt work.
on install I get this:

root@webserver:~# dpkg -i hestia_1.3.1~RC_amd64.deb
(Reading database ... 33218 files and directories currently installed.)
Preparing to unpack hestia_1.3.1~RC_amd64.deb ...
Unpacking hestia (1.3.1~RC) over (1.3.1~RC) ...
dpkg: dependency problems prevent configuration of hestia:
 hestia depends on acl; however:
  Package acl is not installed.
 hestia depends on sysstat; however:
  Package sysstat is not installed.
 hestia depends on zstd; however:
  Package zstd is not installed.

dpkg: error processing package hestia (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 hestia
root@webserver:~# root@webserver:~# dpkg -i hestia_1.3.1~RC_amd64.deb
 hestia depends on zstd; however:
  Package zstd is not installed.

dpkg: error processing package hestia (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 hestia

**Comment by ScIT-Raphael** [comment] 2020-11-15 19:53
apt-get install -f will help, but please dont temove the issue template, it would provide important informations and isnt just decoration.

What's your hestia version? This packages should be installed since a long time, including zstd - which has been released with hestia 1.3.0.

**Comment by Johnzapf** [comment] 2020-11-15 19:57
its a fresh install of Debian 10 all updated. nothing on it.

**Comment by ScIT-Raphael** [comment] 2020-11-15 19:58
and did apt-get install -f now resolved the dependency issues?

**Comment by Johnzapf** [comment] 2020-11-15 19:59
so is this an upgrade install?

**Comment by ScIT-Raphael** [comment] 2020-11-15 19:59
1.3.1 is for upgrade only, yes. Please use the installer for 1.3.0 and install the RC deb package over it.

**Comment by Johnzapf** [comment] 2020-11-15 20:00
ok, my bad.

**Closed as completed by ScIT-Raphael** 2020-11-15 19:59 UTC

**Comment by ScIT-Raphael** [comment] 2020-11-15 20:01
all good, still doesnt explain your ssl issues, let's stick on forum for that one - maybe you want to reach out also in our discord group (link on forum or github readme).

**Comment by Johnzapf** [comment] 2020-11-15 20:04
we will see how the SSL goes with 1.3.1

**Comment by ScIT-Raphael** [comment] 2020-11-15 20:07
there are no changes for the letsencrypt api or scripts, so would probaly be still the same. But can't reproduce your issue on any of ny productiv and test servers, the process is running smooth. Just be sure you havent enabled IPv6 and propper DNS records.

**Comment by Johnzapf** [comment] 2020-11-15 20:13
Well I am not the best with Debian so I am not sure if IPv6 is disabled or not?

DNS should be fine. its not installed on Hestia, that's all handled at GoDaddy and its all set right. and like I said all worked fine on Vesta installed on CentOS, so maybe it is IP6?

**Comment by Johnzapf** [comment] 2020-11-15 20:23
What is the best way to tell if IP6 is disabled. FYI: just tried ssl again and get this Error: Let's Encrypt new auth status 429

**Comment by Johnzapf** [comment] 2020-11-15 20:26
Is the Centos version ready for testing yet? I will be happy to give it a try when it is.

**Comment by ScIT-Raphael** [comment] 2020-11-15 20:30
No, work for centos is still in progress and not testable yet.

429 say that you hit the request limit - have a look at our forum, there are already a lot ot threads handling the 400 and 429 issues.

About ipv6, it tries to verify it, only if you have aaaa (ipv6) dns records.

**Comment by Johnzapf** [comment] 2020-11-15 21:38
ok, thanks.

I disable ip6 and still same 429 issue, will look on the forums.

I posted this as I am not sure it those symbols are supposed to be there.

John


________________________________

**Comment by ScIT-Raphael** [comment] 2020-11-15 21:47
you need to wait, because of the 429 rate limit - probaly around a hour.

The icons are a known issue, we're working on a fix.

**Comment by Johnzapf** [comment] 2020-11-15 21:54
hmm: 429 rate limit, I have been trying for 2 days so I am not sure about the 1 hour time limit?

And again, Vesta went right through on the same URL, all same everything. This was prior to me learning about Hestia.

I am just doing lots of testing. going to get off the windows IIS 10, so far Hestia is doing most all I need, and the performance blows IIS 10 away 🙂




________________________________
