### ISSUE TITLE
ftp upload problem

### ISSUE THREAD

**Issue by daffyyyy** [hestiacp/hestiacp#564] opened 2019-08-06 10:47 UTC
### In a few words, please describe the issue that you're experiencing:
Problem with uploading some files, when i try upload files via ftp some files can't be put.

### What steps did you take when the issue occured? 
1. Log to ftp
2. Navigate to public_html
3. Upload

### Expected behavior:
-----

### Operating system distribution and release:
```
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
```

### Which version of Hestia Control Panel is currently installed?
You can find this information in $HESTIA/conf/hestia.conf by running the following command:
`grep VERSION $HESTIA/conf/hestia.conf`
`VERSION='1.0.4'`

### Which branch are you using?
release

### When did this issue occur? After a clean installation, or after an upgrade?

After clean installation

### Which of the following web server configurations are you using?
- Apache + Nginx (default) <-
- Nginx + PHP-FPM
- Multi-PHP <-
- PHP-FPM + Multi-PHP
- Other (please specify)

### Which of the following server roles are installed on your server?
- DNS <-
- Mail (Dovecot + Exim) <-
- Mail (Exim only)
- MySQL (MariaDB) <-
- PostgreSQL

### In order to better assist, please post any relevant log information below:
```
   Sat Aug 3 08:54:25 2019 [pid 5026] [admin] OK LOGIN: Client “83.26.166.129”
    Sat Aug 3 08:54:26 2019 [pid 5028] [admin] FAIL UPLOAD: Client “83.26.166.129”, “/web/daffyy.pro/public_html/img/logo.png”, 0.00Kbyte/sec
    Sat Aug 3 08:54:27 2019 [pid 5028] [admin] FAIL UPLOAD: Client “83.26.166.129”, “/web/daffyy.pro/public_html/img/logo.png”, 0.00Kbyte/sec
    Sat Aug 3 08:54:28 2019 [pid 5028] [admin] FAIL UPLOAD: Client “83.26.166.129”, “/web/daffyy.pro/public_html/img/logo.png”, 0.00Kbyte/sec
```

### Related issues or forum threads:
https://forum.hestiacp.com/t/ftp-upload-problem/127

### Additional notes:
Problem exist not only on admin account

**Comment by Lupul** [comment] 2019-08-11 14:04
Issue is affecting only FTP file transfers as you mentioned here: https://forum.hestiacp.com/t/ftp-upload-problem/127/5 , SFTP is working fine so folder/file permission are good.

I could reproduce a similar behavior when uploading a WP folder trough ftp, some files took more than 2-3min to upload(<100kb), some of them timed-out even when uploading these files one by one.

I plan to test a clean Ubuntu1804 install with just vsftpd package to see if the problem is present there also, to have a better understanding of the problem.

But as general note FTP should never be used today (this was true also more than a decade ago),  clear-text auth and file transfer are no joke.

**Comment by ScIT-Raphael** [comment] 2019-12-27 19:56
Due to the explanation of @Lupul I'll close this issue report.

**Closed as completed by ScIT-Raphael** 2019-12-27 19:56 UTC
Labels: bug, web
