### ISSUE TITLE
[Feature] Auto login for PHPmyAdmin

### ISSUE THREAD

**Issue by ozgurerdogan** [hestiacp/hestiacp#1460] opened 2020-12-12 18:53 UTC
It is soo useful when control panel has auto login feature for webmail and phpmyadmin.

**Comment by ScIT-Raphael** [comment] 2020-12-12 18:57
Hi @ozgurerdogan 

Thanks for your request, which is basicly a duplicate of https://github.com/hestiacp/hestiacp/issues/523.

I'll check in dev chat if we still got the same situation, but nearly sure we have. I may close this kssue later if I got the feedback.

**Comment by johnnyq** [comment] 2020-12-14 17:01
The phpmyadmin option would be a bonus. Its impossible for auto mail login with Encrypted passwords

**Comment by jaapmarcus** [comment] 2020-12-17 10:06
As Webmail is technical "impractical"  and personally don't see the need for it.  Also with privacy concerns...   I would really like to get some notifications if some body enters my email unauthorised...

For PHPmyAdmin it is personally an different story as there is currently an need for it. Web devs for example....

PHPmyadmin supports Single Sing On on 2 "different way" 

One via "Username" + Password set inside in session how ever those data need to have an un encrypted password. Currently not possible as we only save the password() out put in our system.

Or secondly create an "Second" User with an random username + random password  and Grant is "full" access to the  database and deletes it after x hour.

**Comment by ozgurerdogan** [comment] 2020-12-17 10:12
Both are must have features. For debugging purposes. Commercial cpanels already have such features. Otherwise they would would not. This means admins requested these features.

**Comment by ScIT-Raphael** [comment] 2020-12-17 10:27
Just do be clear: pma is in discussion and will be probaly implemented, mail access is a no go and was declined from the dev team.

**Comment by jaapmarcus** [comment] 2020-12-31 15:44
Fixed and will be released in 1.4.0

**Closed as completed** 2020-12-31 15:44 UTC
Labels: feature, enhancement
