### ISSUE TITLE
500 error after autoupdate to  v1.3.1

### ISSUE THREAD

**Issue by tano221087** [hestiacp/hestiacp#1401] opened 2020-11-18 07:55 UTC
My websites are down after hestiacp autoupgraded to  v1.3.1

**Please include as much information as possible in your issue report, such as the configuration of your server and any troubleshooting steps that you've already performed.**

**NOTE: Do not include any personal or sensitive information, such as email addresses or passwords.**

===

### In a few words, please describe the issue that you're experiencing:
Please enter your answer here (e.g. When I try adding a web domain, an error message appeared stating that the php-fpm pool did not exist).

### What steps did you take when the issue occured? 
1. Ex.: Click on the "Web" tab.
2. Ex.: Click on "Add Web Domain".
3. Ex.: Attempted to add a domain and received an Internal Server Error.

### Expected behavior:
Please enter your answer here (e.g. the web domain should have been added successfully).

### Operating system:
Please enter your answer here (e.g. Ubuntu 20.04 LTS)

### Hestia Control Panel version:
Please enter your answer here (e.g. 1.3.0). 

### Additional notes:
If there is anything else that you'd like us to know about this issue that will help us diagnose and troubleshoot more effectively, such as links to forum posts or other discussions, please feel free to share here.

**Comment by ScIT-Raphael** [comment] 2020-11-18 07:56
Please fill out the issue report and check your services.

**Comment by tano221087** [comment] 2020-11-18 08:06
services are all ok

**Comment by ScIT-Raphael** [comment] 2020-11-18 08:08
Backend up and running? Did you checked the web logs where you get a 500 internal? /home/user/web/domain.tld/log

**Comment by jaapmarcus** [comment] 2020-11-18 08:09
Please supply us with update log..

**Comment by tano221087** [comment] 2020-11-18 08:18
2020/11/18 09:14:27 [error] 60706#60706: *558 connect() failed (111: Connection refused) while connecting to upstream, client: 95.234.98.236, server: direttasicilia.it, request: "GET /2020/11/17/ok-a-spesa-in-altro-comune-se-si-puo-risparmiare-il-governo-chiarisce-il-dpcm/ HTTP/2.0", upstream: "https://144.91.125.145:8443/2020/11/17/ok-a-spesa-in-altro-comune-se-si-puo-risparmiare-il-governo-chiarisce-il-dpcm/", host: "www.direttasicilia.it"
2020/11/18 09:14:28 [error] 60706#60706: *545 connect() failed (111: Connection refused) while connecting to upstream, client: 79.20.222.79, server: direttasicilia.it, request: "GET /wp-content/uploads/2020/05/190128-Palermo-Sicily-Italy-IMG00-1200x675-1.jpg HTTP/2.0", upstream: "https://144.91.125.145:8443/wp-content/uploads/2020/05/190128-Palermo-Sicily-Italy-IMG00-1200x675-1.jpg", host: "www.direttasicilia.it", referrer: "https://it.images.search.yahoo.com/search/images;_ylt=AwrJRCDH17RfinwAs1Lc5olQ;_ylu=Y29sbwNpcjIEcG9zAzEEdnRpZAMEc2VjA3BpdnM-?p=sicilia&fr2=piv-web&fr=mcafee"
2020/11/18 09:14:29 [error] 60706#60706: *558 connect() failed (111: Connection refused) while connecting to upstream, client: 95.234.98.236, server: direttasicilia.it, request: "GET /favicon.ico HTTP/2.0", upstream: "https://144.91.125.145:8443/favicon.ico", host: "www.direttasicilia.it", referrer: "https://www.direttasicilia.it/2020/11/17/ok-a-spesa-in-altro-comune-se-si-puo-risparmiare-il-governo-chiarisce-il-dpcm/"
2020/11/18 09:14:30 [error] 60706#60706: *565 connect() failed (111: Connection refused) while connecting to upstream, client: 151.19.161.158, server: direttasicilia.it, request: "GET /2020/11/17/ok-a-spesa-in-altro-comune-se-si-puo-risparmiare-il-governo-chiarisce-il-dpcm/ HTTP/2.0", upstream: "https://144.91.125.145:8443/2020/11/17/ok-a-spesa-in-altro-comune-se-si-puo-risparmiare-il-governo-chiarisce-il-dpcm/", host: "www.direttasicilia.it", referrer: "http://m.facebook.com/"

**Comment by ScIT-Raphael** [comment] 2020-11-18 09:09
`545 connect() failed (111: Connection refused) while connecting to upstream`

Still you didnt share your installation, if it is apache2+nginx or nginx only. If apache2, check if the service is up and running.

**Comment by tano221087** [comment] 2020-11-18 09:18
apache2+nginx, apache2 is running 
phpmyadmin is down too

**Comment by ScIT-Raphael** [comment] 2020-11-18 09:24
and the system status of apache2? The logs of it aswell? What's the status of your php7.3-fpm service? Something seems to be down...

**Comment by tano221087** [comment] 2020-11-18 09:27
where can i found it?

**Comment by ScIT-Raphael** [comment] 2020-11-18 09:32
Find what? Service status? -> https://www.man7.org/linux/man-pages/man1/systemctl.1.html

**Comment by tano221087** [comment] 2020-11-18 09:35
services are all green in hestiacp

**Comment by ScIT-Raphael** [comment] 2020-11-18 09:36
Infact it doesnt seem to be a reproduceable case, I'm going to close this issue. Please stick to our forum or discord chat for further support (both links on readme.md), this is a server related problem, probaly occured due to the service restart process of the hestia update.

**Closed as completed by ScIT-Raphael** 2020-11-18 09:36 UTC
Labels: invalid

**Comment by tano221087** [comment] 2020-11-18 09:41
I rebooted server but nothing

**Comment by ScIT-Raphael** [comment] 2020-11-18 09:53
Reboot the server will not resolve any configuration issue... Please stick as adviced to forum or discord - this is not a issue for the github tracker, we can't do anything here, it's a local issue with your server.
