### ISSUE TITLE
Lets Encrypt Error 15

### ISSUE THREAD

**Issue by LeBaux** [hestiacp/hestiacp#536] opened 2019-07-12 16:47 UTC
### In a few words, please describe the issue that you're experiencing:

Installed hestia on clean & updated debian 9:
`bash hst-install.sh -w yes -o yes -k no -c no -t no`

Please enter your response here (e.g. When I click on the Web tab, a blank page is displayed).
-

### What steps did you take when the issue occured? 

added a domain EXAMPLE.com
trying adding lets encrypt via gui
result:
Error: Let's Encrypt acc registration failed

### Expected behavior:
Successful creation of Lets Encrypt cert.

### Operating system distribution and release:
Debian 9 (up to date)

### Which version of Hestia Control Panel is currently installed?
1.0.4

### Which branch are you using?
https://raw.githubusercontent.com/hestiacp/hestiacp/release/install/hst-install.sh

### When did this issue occur? After a clean installation, or after an upgrade?
right after fresh install

### Which of the following web server configurations are you using?

`bash hst-install.sh -w yes -o yes -k no -c no -t no`

### Which of the following server roles are installed on your server?

`bash hst-install.sh -w yes -o yes -k no -c no -t no`

### In order to better assist, please post any relevant log information below:
Tip: Most log files can be found under ***/var/log/***.

/usr/local/hestia/log/error.log
2019-07-12 18:39:20 v-add-letsencrypt-user  'admin' [Error 15]
2019-07-12 18:39:20 v-add-letsencrypt-domain  'admin' 'DOMAIN.com' 'www.DOMAIN.com' '' [Error 15]

### Related issues or forum threads:
-

### Additional notes:
The same domain works with VestaCP, implying that DNS is set up correctly. The domain has HSTS (from the previous install).

**Comment by ScIT-Raphael** [comment] 2019-07-12 17:01
Most time this error occurs due to a invalid email address inside the useraccount. Can you check if it is valid?

**Comment by LeBaux** [comment] 2019-07-12 17:14
I tried with 2 different fresh installs. I made sure email provided via installer GUI was valid. I didnt check anywhere else. Is there more detailed log somewhere? It was valid gmail address both times.

**Comment by ScIT-Raphael** [comment] 2019-07-12 18:14
The current let's encrypt stack does not provide "much" log informations, this is on our roadmap for a rework :).

I just verified if it works on our test system (Debian 9, up to date, Hetzner Cloud), installed hestia with your provided installation command - not able to reproduce the issue here:
![LE_Test](https://user-images.githubusercontent.com/13765400/61149424-6c1dcd00-a4e1-11e9-898f-897cda81ba98.JPG)

You could try to add your user account over cli with the following command:
v-add-letsencrypt-user username

Where and how do you host your server?

**Comment by LeBaux** [comment] 2019-07-12 19:16
I setup the server with ISPconfig, but since you are so proactive I am going to wipe it again :smile: So far I can tell LetsEncrypt works with both VestaCP and ISPconfig out of the box. This points to faulty script in Hestia. Sadly, without better logging, I think this is hit and miss debugging.

My VPS is based on OpenVZ. Other web panels work without problems here.

I tried default install, and `bash hst-install.sh -w yes -o yes -k no -c no -t no`. Now for the 3rd. time I tried different domain. Still the same error. Also:

```
root@server:~# v-add-letsencrypt-user admin
Error: Let's Encrypt acc registration failed 

root@server:~# v-add-letsencrypt-user admin2
Error: LetsEncrypt user account doesn't exist
```

I would still like to help you figure this out. This is a staging server, so I can give you root access to clean and updated install of Debian 9; and 2 domains pointing towards the server IP. I can send you login details over mail, provided you care enough to look into it.

**Comment by ScIT-Raphael** [comment] 2019-07-12 19:19
A bit weird, the script wasnt changed since vesta (at least the v-add-letsencrypt-user one). Can you send a mail with the login credentials to info@hestiacp.com? Would like to take a short look.

**Comment by LeBaux** [comment] 2019-07-12 19:21
I will send it over in a bit, with as many details as possible.

**Comment by ScIT-Raphael** [comment] 2019-07-12 19:35
Thanks, will stay online for around the next 2 hrs.

**Comment by cmstew** [comment] 2019-07-12 19:39
Just a thought. I had trouble with LetsEncrypt and Hestia on Digital Ocean Debian install and the only thing that I changed to make it work, was changing the IP from the private one to the public one in the Hestia IP Settings. The setting for IP will only show up if you have more than one.

**Comment by LeBaux** [comment] 2019-07-12 19:52
@cmstew the domain I am trying to generate cert for is resolving for both A and AAAA. Plus, I used identical virtual server setup with Vesta/ISPconfig and both generated the cert.

@ScIT-Raphael I've sent you an email with login details and short video explanation.

**Comment by cmstew** [comment] 2019-07-12 20:07
@LeBaux I meant in the Hestia settings, not in your DNS. If your domain is attached to a local ip in Hestia and you don't have a proper NAT setup to forward your Public IP, Letsencrypt won't be able to find the .well-known folder.

Hopefully SclT-Raphael can sort it out for you. :)

**Comment by LeBaux** [comment] 2019-07-12 20:16
We exchanged emails with @ScIT-Raphael and for now, the culprit seems to be Hestia not playing nice with the server having ipv6 assigned or some other routing issue. I like SSL but boy do I hate this dance.

**Comment by cmstew** [comment] 2019-07-12 20:20
When it works, it's awesome, but it can be troublesome at times. Good luck. :)

**Comment by ScIT-Raphael** [comment] 2019-07-12 20:39
Ok, found the issue: OpenVZ has some troubles with iptables, so it limits (at least) the dns communication which caused in a timeout to reach the let's encrypt api.

I brought you back the "vesta" version of a fix for this issue, you've got now a valid cert for the hostname domain (used v-add-letsencrypt-host): https://github.com/hestiacp/hestiacp/commit/3e8d711205193237024a89058994fa44a99386f7#diff-f10962a1b624d30cb1dbdd0a1c3a6e96 

BUT: We, or better I removed the part because of a valid reason - it disable your firewall without any information, which will also stop fail2ban to work properly. If you allow, I would suggest to step away from OpenVZ (last version was in 2016) and use for example Proxmox or a service like Hetzner Cloud - both are tested and working perfectly with hestia.

Hestia does now work on your system, but a new release will flush the manualy adjusted code and stops (at least) dns communication) again.

**Closed as completed by ScIT-Raphael** 2019-07-12 20:39 UTC

**Comment by LeBaux** [comment] 2019-07-13 09:42
Just an update on OpenVZ topic. As you said, maintaining support for legacy software is not feasible. The VPS provider I am using is switching to https://vpsadminos.org/ currently we are in the testing stage. I will test Hestia compatibility on staging server.

Also, if you are interested why go through all that trouble of making custom hypervisor for container virtualization https://www.youtube.com/watch?v=ZJnZv2TE5_Q (eng, 30min.).
