### ISSUE TITLE
[BUG] Creating a IDN-domain stops apache

### ISSUE THREAD

**Issue by trommegutten** [hestiacp/hestiacp#2029] opened 2021-07-30 08:03 UTC
**Describe the bug**
If you add a IDN-domain with special characters in the hestia web eg. "bløst.com" or "blæån.com" this will cause apache to stop and other sites to go offline. If you add the IDN-version instead eg "xn--blst-hra.com" or "xn--bln-vlae.com" apache will run, LetsEncrypt will issue certificate and the webpage will show up in the browser.

**To Reproduce**
This does not work:
1. Add a domain "bløst.com"
2. The apache server stops
3. Domain name does not show under domain

This works/workaround:
1. Add a domain "xn--blst-hra.com" (IDN-converted bløst.com)
2. The domain name show up under domains as "xn--blst-hra.com" (IDN-converted bløst.com)
3. Lets Encrypt issue certificate 
4. The webpage "bløst.com" displays as normal/SSL in a browser

**Expected behavior**
The domain (eg. bløst.com) should be added as normal
The domain (eg. bløst.com) should be displayed in the control panel.

**Operating system:**
Ubuntu 20.04 LTS

**Hestia Control Panel version:**
1.4.9

**Additional context**
https://github.com/hestiacp/hestiacp/pull/1640

**Comment by jaapmarcus** [comment] 2021-07-30 09:07
What is you setup? Nginx + Apache2 or only apache2?

**Comment by trommegutten** [comment] 2021-07-30 09:14
Standard installation, Nginx and Apache2 are running.

**Comment by jaapmarcus** [comment] 2021-07-30 09:48
Strange can config the issue on Apache2  but no problem on Nginx standalone.  Will need to investigate the issue 

The issue is that server name remains empty:
<VirtualHost xx.xx.xxx.xx:8080>

    ServerName 
    ServerAlias 
    ServerAdmin info@bløst.com
...

And so on

**Comment by jaapmarcus** [comment] 2021-07-30 13:48
Have added a few test 
https://drone.hestiacp.com/hestiacp/hestiacp/111/1/4

It seems that via command line  v-add-web-domain test bløst.com works fine. So it must be an escaping thing

**Comment by jaapmarcus** [comment] 2021-07-30 15:05
@trommegutten  please check your locale. 

If it is C.UTF8  try changing it to en_US.UTF8 and it should work fine. How still not perfect

**Comment by jaapmarcus** [comment] 2021-08-10 09:10
Please check you locale.  I will close the issue for now

**Closed as completed by jaapmarcus** 2021-08-10 09:10 UTC
Labels: bug, web
