### ISSUE TITLE
cant browse web pages error 500

### ISSUE THREAD

**Issue by darkworks** [hestiacp/hestiacp#855] opened 2020-06-09 13:41 UTC
### Please fill in the relevant sections below and remove those which do not apply.

**To help aid our developers in debugging your issue we ask that you include as much information as possible, including the configuration of your server and troubleshooting steps already performed.**

**Please DO NOT include any personal or sensitive information in your issue reports, including usernames or passwords!**

===

### In a few words, please describe the issue that you're experiencing:
well i freshly installed hestiacp on my server VM which have nat ip , and i found that whenever i try to visit site i get 500 error after about min of waiting and same happening with phpmyadmin too. i checked apache error log nothing serious there , all services are running .

### What steps did you take when the issue occured? 
-install hestiacp on debian 4 on nat ip environment
 - login to panel
- add subdomain like  test.mydomain.com
- visit it and u will see 500 error

### Expected behavior:
should load webpages

### Does this issue always occur, or is it intermittent?
ya it occur with hestia installation , although i had installed original vestacp which is working ok just that with nat ip i was not able to auto generate letsencrypt certificates from web UI was getting 400 status code but could from vesta cli so i thought should check on, with hestia so i install and i was able to generate letsencrypt certs from web UI but the problem is it would not load webpage will throw 500 error

### Operating system distribution and release:
Debian 10.4 buster and latest hestia 1.1.11

### Which version of Hestia Control Panel is currently installed?
latest 1.1.11

Please enter your answer here (e.g. 1.1.0)

### Which branch are you using?
release

### When did this issue occur? After a clean installation, or after an upgrade?
clean

**Note:** If you have upgraded from an older release on an existing server, please let us know which version was previously installed if at all possible.

### Which of the following web server configurations are you using?
- Apache + Nginx (default)
- Nginx + PHP-FPM
- Multi-PHP
- PHP-FPM + Multi-PHP
- mariadb

### In order to better assist, please post any relevant log information below:

```
[Tue Jun 09 01:33:56.819788 2020] [mpm_prefork:notice] [pid 799] AH00169: caught SIGTERM, shutting down
[Tue Jun 09 01:34:03.116776 2020] [ssl:warn] [pid 5330] AH01909: 192.168.0.104:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 09 01:34:03.117053 2020] [suexec:notice] [pid 5330] AH01232: suEXEC mechanism enabled (wrapper: /usr/lib/apache2/suexec)
[Tue Jun 09 01:34:03.224378 2020] [ssl:warn] [pid 5331] AH01909: 192.168.0.104:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 09 01:34:03.232351 2020] [mpm_prefork:notice] [pid 5331] AH00163: Apache/2.4.38 (Debian) mod_fcgid/2.3.9 OpenSSL/1.1.1g configured -- resuming normal operations
[Tue Jun 09 01:34:03.232409 2020] [core:notice] [pid 5331] AH00094: Command line: '/usr/sbin/apache2'
[Tue Jun 09 01:36:14.299860 2020] [mpm_prefork:notice] [pid 5331] AH00171: Graceful restart requested, doing restart
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using test.domain.com. Set the 'ServerName' directive globally to suppress this message
[Tue Jun 09 01:36:14.558246 2020] [ssl:warn] [pid 5331] AH01909: 192.168.0.104:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 09 01:36:14.558771 2020] [mpm_prefork:notice] [pid 5331] AH00163: Apache/2.4.38 (Debian) mod_fcgid/2.3.9 OpenSSL/1.1.1g configured -- resuming normal operations
[Tue Jun 09 01:36:14.558806 2020] [core:notice] [pid 5331] AH00094: Command line: '/usr/sbin/apache2'
```

Nginx log

```
2020/06/08 22:52:03 [error] 9186#9186: *23 upstream timed out (110: Connection timed out) while connecting to upstream, client: 192.140.150.40, server: test.domain.com, request: "GET / HTTP/1.1", upstream: "http://192.168.0.104:8080/", host: "test.domain.com"
2020/06/08 22:53:29 [error] 9186#9186: *26 upstream timed out (110: Connection timed out) while connecting to upstream, client: 192.140.150.40, server: test.domain.com, request: "GET / HTTP/1.1", upstream: "http://192.168.0.104:8080/", host: "test.domain.com"
2020/06/08 22:54:44 [error] 12257#12257: *33 upstream timed out (110: Connection timed out) while connecting to upstream, client: 192.140.150.40, server: test.domain.com, request: "GET / HTTP/1.1", upstream: "http://192.168.0.104:8080/", host: "test.domain.com"
2020/06/08 22:55:20 [error] 12257#12257: *33 upstream timed out (110: Connection timed out) while connecting to upstream, client: 192.140.150.40, server: test.domain.com, request: "GET / HTTP/1.1", upstream: "http://192.168.0.104:8080/", host: "test.domain.com"
2020/06/09 01:33:53 [error] 12257#12257: *77 upstream timed out (110: Connection timed out) while connecting to upstream, client: 192.140.150.40, server: _, request: "GET /phpmyadmin/ HTTP/1.1", upstream: "http://192.168.0.104:8080/phpmyadmin/", host: "206.200.105.103"
2020/06/09 01:34:47 [error] 12257#12257: *81 upstream timed out (110: Connection timed out) while connecting to upstream, client: 192.140.150.40, server: _, request: "GET /phpmyadmin/ HTTP/1.1", upstream: "http://192.168.0.104:8080/phpmyadmin/", host: "206.200.105.103"
2020/06/09 01:34:55 [error] 12257#12257: *84 upstream timed out (110: Connection timed out) while connecting to upstream, client: 192.140.150.40, server: test.domain.com, request: "GET / HTTP/1.1", upstream: "http://192.168.0.104:8080/", host: "test.domain.com"
2020/06/09 01:35:17 [error] 12257#12257: *81 upstream timed out (110: Connection timed out) while connecting to upstream, client: 192.140.150.40, server: _, request: "GET /phpmyadmin/ HTTP/1.1", upstream: "http://192.168.0.104:8080/error/50x.html", host: "206.200.105.103"
2020/06/09 01:36:50 [error] 12257#12257: *90 upstream timed out (110: Connection timed out) while connecting to upstream, client: 192.140.150.40, server: test.domain.com, request: "GET / HTTP/1.1", upstream: "http://192.168.0.104:8080/", host: "test.domain.com"
2020/06/09 02:19:04 [error] 12257#12257: *114 upstream timed out (110: Connection timed out) while connecting to upstream, client: 212.129.3.22, server: _, request: "GET / HTTP/1.1", upstream: "http://192.168.0.104:8080/", host: "206.200.105.103"
2020/06/09 02:19:34 [error] 12257#12257: *114 upstream timed out (110: Connection timed out) while connecting to upstream, client: 212.129.3.22, server: _, request: "GET / HTTP/1.1", upstream: "http://192.168.0.104:8080/error/50x.html", host: "206.200.105.103"
2020/06/09 04:28:04 [error] 12257#12257: *163 upstream timed out (110: Connection timed out) while connecting to upstream, client: 192.140.150.40, server: test.domain.com, request: "GET / HTTP/1.1", upstream: "http://192.168.0.104:8080/", host: "test.domain.com"
2020/06/09 04:30:51 [error] 12257#12257: *184 upstream timed out (110: Connection timed out) while connecting to upstream, client: 192.140.150.40, server: test.domain.com, request: "GET / HTTP/1.1", upstream: "http://192.168.0.104:8080/", host: "test.domain.com"
2020/06/09 04:41:51 [error] 12257#12257: *192 upstream timed out (110: Connection timed out) while connecting to upstream, client: 190.142.193.9, server: test.domain.com, request: "GET / HTTP/1.1", upstream: "http://192.168.0.104:8080/", host: "test.domain.com"
```

### Related issues or forum threads:
Find something that might be related to this? Please let us know by adding any relevate issue numbers or URLs here (e.g. issue #000 or https://forum.hestiacp.com/...)

### Additional notes:
If there is anything else that you'd like us to know about this issue, feel free to share here.

**Comment by ScIT-Raphael** [comment] 2020-06-09 13:52
If you get a 500 error message after one minute, it is also possible that there fails somewhere at nginx. Please share your nginx logs and update your webserver configuration, probaly also share the used installation string so we have more informations.

**Comment by darkworks** [comment] 2020-06-09 14:12
ok i have added nginx log , looks like something wrong with server name 

about installation i followed instruction it https://www.hestiacp.com/
- wget https://raw.githubusercontent.com/hestiacp/hestiacp/release/install/hst-install.sh
- bash hst-install.sh 

after that mostly yes yes   default installation

screenshot

![image](https://user-images.githubusercontent.com/12841788/84158604-7f387480-aa85-11ea-9ecc-de5365a83c86.png)
![image](https://user-images.githubusercontent.com/12841788/84158693-9a0ae900-aa85-11ea-99c5-83d61043b485.png)

**Comment by ScIT-Raphael** [comment] 2020-06-09 14:59
Looks good from here, are you sure that the 500 internal server error doesnt occur because of the website data itself? If you test it with a new domain without any additional data, does it work properly?

**Comment by darkworks** [comment] 2020-06-09 15:02
there was no data in it just default index.html coming soon page. and ya i
delete it multiple time and created it. but same. also when i add database
and click on phpmyadmin url it also not load same 500 error.

**Comment by ScIT-Raphael** [comment] 2020-06-11 06:52
Just tried to reproduce, but all is working properly here. Did you managed to get it working?

**Comment by darkworks** [comment] 2020-06-11 08:38
> Just tried to reproduce, but all is working properly here. Did you managed to get it working?

no i was not able to fix the issue , i create another vm with vesta and its working ok ,however that hestia machine i have not deleted yet so if you can give me your mail i can give u access to it

**Comment by ScIT-Raphael** [comment] 2020-06-11 08:39
Send us a mail to info@hestiacp.com, I'll have a look.

**Comment by darkworks** [comment] 2020-06-11 09:03
> Send us a mail to [info@hestiacp.com](mailto:info@hestiacp.com), I'll have a look.

the machine started working
looks like the problem is in ip change : /edit/ip/
earlier i had active domain on some another ip so i had changed the NAT now i reverted back to the installation IP and after reboot it start working , so looks like the ip is not changed fully on backend

**Comment by ScIT-Raphael** [comment] 2020-06-11 09:06
Glad it worked now, going to close the issue now.

**Comment by darkworks** [comment] 2020-06-11 09:07
the hestia fork is great as official vesta seems dead. i was using myveta of depca , so do you have any plan to add secret url and other features from depca my vesta fork because its good for security make every vesta installation safe unlike previously all vesta installations were because of the flaw in vesta panel.

**Closed as completed by ScIT-Raphael** 2020-06-11 09:06 UTC

**Comment by darkworks** [comment] 2020-06-11 09:12
however there is still issue with phpmyadmin access when i visit

https://ip_address/phpmyadmin/  it says   ip_address refused to connect 

so any fix for it or should i send access so that u can  have look ,

**Comment by jaapmarcus** [comment] 2020-06-11 09:13
Please use hostname

my.hostname.tld/phpmyadmin

**Comment by darkworks** [comment] 2020-06-11 09:14
ok
