### ISSUE TITLE
Firewall - Create New IP List (Format error)

### ISSUE THREAD

**Issue by avcvv** [hestiacp/hestiacp#1039] opened 2020-08-01 14:11 UTC
Impossible to add spamhaus list to firewall, got error

example: https://www.spamhaus.org/drop/drop.txt

i took list from this topic https://forum.hestiacp.com/t/how-to-ipset-blocking-with-csf/1249 maybe you can do adaptation them format to hestia

**Comment by jaapmarcus** [comment] 2020-08-01 14:21
You will need to preprocess those lists
See https://github.com/hestiacp/hestiacp/blob/main/install/deb/firewall/ipset/blacklist.sh

If you want to add the following lists

You can use the blacklist options as it already in it..

**Comment by jaapmarcus** [comment] 2020-08-01 14:59
Just check with last version:

```
root@dev:/usr/local/hestia/bin# v-update-sys-hestia-git hestiacp staging/fixes install
 v-add-firewall-ipset test http://lists.blocklist.de/lists/all.txt 
Error: Populating ipset table
root@dev:/usr/local/hestia/bin# v-add-firewall-ipset test https://www.spamhaus.org/drop/drop.txt v4
Error: Populating ipset table
```

**Comment by Lupul** [comment] 2020-08-01 17:25
```bash

wget https://raw.githubusercontent.com/hestiacp/hestiacp/staging/fixes/bin/v-add-firewall-ipset -O $HESTIA/bin/v-add-firewall-ipset

$HESTIA/bin/v-delete-firewall-ipset test-all
# Error: ipset listname test-all doesn't exist

$HESTIA/bin/v-add-firewall-ipset test-all 'https://lists.blocklist.de/lists/all.txt'

ipset list test-all -t
# Name: test-all
# Type: hash:net
# Revision: 6
# Header: family inet hashsize 16384 maxelem 1048576
# Size in memory: 899800
# References: 0
# Number of entries: 28468

```

**Comment by ScIT-Raphael** [comment] 2020-08-01 19:40
fixed: https://github.com/hestiacp/hestiacp/pull/1040#merged-event

**Closed as completed by ScIT-Raphael** 2020-08-01 19:40 UTC

**Comment by Lupul** [comment] 2020-08-01 19:52
@avcvv Can you confirm the ip list loads ok on your side too with the latest fix? 

```bash
wget https://raw.githubusercontent.com/hestiacp/hestiacp/staging/fixes/bin/v-add-firewall-ipset -O $HESTIA/bin/v-add-firewall-ipset

$HESTIA/bin/v-add-firewall-ipset test-drop 'https://www.spamhaus.org/drop/drop.txt'
```

**Comment by avcvv** [comment] 2020-08-01 20:54
```
# wget https://raw.githubusercontent.com/hestiacp/hestiacp/staging/fixes/bin/v-add-firewall-ipset -O $HESTIA/bin/v-add-firewall-ipset
--2020-08-01 22:53:39--  https://raw.githubusercontent.com/hestiacp/hestiacp/staging/fixes/bin/v-add-firewall-ipset
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6590 (6.4K) [text/plain]
Saving to: ‘/usr/local/hestia/bin/v-add-firewall-ipset’

/usr/local/hestia/bin/v-add-firewall-ipset         100%[================================================================================================================>]   6.44K  --.-KB/s    in 0s      

2020-08-01 22:53:39 (24.9 MB/s) - ‘/usr/local/hestia/bin/v-add-firewall-ipset’ saved [6590/6590]

[root@:~]# v-add-firewall-ipset test-drop 'https://www.spamhaus.org/drop/drop.txt'

Error: Populating ipset table
```


Now i see empty records in table

```
# ipset list
Name: Spamhaus
Type: hash:net
Revision: 6
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 344
References: 0
Number of entries: 0
Members:

Name: Spamhaus-tmp
Type: hash:net
Revision: 6
Header: family inet hashsize 1024 maxelem 1048576
Size in memory: 344
References: 0
Number of entries: 0
Members:

Name: test-drop
Type: hash:net
Revision: 6
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 344
References: 0
Number of entries: 0
Members:

Name: test-drop-tmp
Type: hash:net
Revision: 6
Header: family inet hashsize 1024 maxelem 1048576
Size in memory: 344
References: 0
Number of entries: 0
Members:
```

**Comment by Lupul** [comment] 2020-08-01 21:51
I can't reproduce the issue on debian 10 and ubuntu 18.04
Can you upload somewhere the content of `$HESTIA/data/firewall/ipset/test-drop.v4.iplist` ?

**Comment by avcvv** [comment] 2020-08-01 22:15
> $HESTIA/data/firewall/ipset/test-drop.v4.iplist

```
# ls $HESTIA/data/firewall/ipset/
blacklist.sh  Spamhaus.v4.iplist  test-drop.v4.iplist
```

 files has correct records, how to execute them?

**Comment by Lupul** [comment] 2020-08-01 22:24
You can't use them as they currently are, "Populating ipset table" error means ipset tool is rejecting some of the entries in those files.

**Comment by avcvv** [comment] 2020-08-01 22:49
what to do?

**Comment by Lupul** [comment] 2020-08-02 07:01
Can you upload somewhere the content of $HESTIA/data/firewall/ipset/test-drop.v4.iplist ?
What OS are you using, seem like you didn't mentioned that previously,

**Comment by avcvv** [comment] 2020-08-02 10:18
Deb10,

```
# ls $HESTIA/data/firewall/ipset/
blacklist.sh  Spamhaus.v4.iplist  test-drop.v4.iplist
[root@:~]# cat $HESTIA/data/firewall/ipset/test-drop.v4.iplist
1.10.16.0/20 ; SBL256894
1.19.0.0/16 ; SBL434604
1.32.128.0/18 ; SBL286275
2.56.255.0/24 ; SBL444288
2.59.200.0/22 ; SBL463003
5.134.128.0/19 ; SBL270738
5.183.60.0/22 ; SBL463004
5.188.10.0/23 ; SBL402741
23.92.80.0/20 ; SBL372561
```

**Comment by Lupul** [comment] 2020-08-02 12:03
Tested again on another debian10 server, but I still can't reproduce,
please check the md5sum of `v-add-firewall-ipset` script
 
```bash
root@:~$  wget https://raw.githubusercontent.com/hestiacp/hestiacp/staging/fixes/bin/v-add-firewall-ipset -O $HESTIA/bin/v-add-firewall-ipset

root@:~$ md5sum $HESTIA/bin/v-add-firewall-ipset
1d8c199699e66fb6d2e32f9a0ceab93a  /usr/local/hestia/bin/v-add-firewall-ipset

root@:~$ $HESTIA/bin/v-add-firewall-ipset test-drop 'https://www.spamhaus.org/drop/drop.txt'

root@:~$ head -n 10 $HESTIA/data/firewall/ipset/test-drop.v4.iplist
1.10.16.0/20
1.19.0.0/16
1.32.128.0/18
2.56.255.0/24
2.59.200.0/22
5.134.128.0/19
5.183.60.0/22
5.188.10.0/23
23.92.80.0/20
24.233.0.0/19
```

**Comment by avcvv** [comment] 2020-08-02 12:05
```
[root@:~]# wget https://raw.githubusercontent.com/hestiacp/hestiacp/staging/fixes/bin/v-add-firewall-ipset -O $HESTIA/bin/v-add-firewall-ipset
--2020-08-02 14:04:25--  https://raw.githubusercontent.com/hestiacp/hestiacp/staging/fixes/bin/v-add-firewall-ipset
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6590 (6.4K) [text/plain]
Saving to: ‘/usr/local/hestia/bin/v-add-firewall-ipset’

/usr/local/hestia/bin/v-add-firewall-ipset         100%[================================================================================================================>]   6.44K  --.-KB/s    in 0s      

2020-08-02 14:04:25 (18.5 MB/s) - ‘/usr/local/hestia/bin/v-add-firewall-ipset’ saved [6590/6590]

[root@:~]# md5sum $HESTIA/bin/v-add-firewall-ipset
1d8c199699e66fb6d2e32f9a0ceab93a  /usr/local/hestia/bin/v-add-firewall-ipset
[root@:~]# $HESTIA/bin/v-add-firewall-ipset test-drop 'https://www.spamhaus.org/drop/drop.txt'
Error: Populating ipset table
[root@:~]# head -n 10 $HESTIA/data/firewall/ipset/test-drop.v4.iplist
1.10.16.0/20 ; SBL256894
1.19.0.0/16 ; SBL434604
1.32.128.0/18 ; SBL286275
2.56.255.0/24 ; SBL444288
2.59.200.0/22 ; SBL463003
5.134.128.0/19 ; SBL270738
5.183.60.0/22 ; SBL463004
5.188.10.0/23 ; SBL402741
23.92.80.0/20 ; SBL372561
24.233.0.0/19 ; SBL210084
```

**Comment by avcvv** [comment] 2020-08-02 12:11
I deleted all files in $HESTIA/data/firewall/ipset/
looks like error was due comments like ; SBL256894 because file appended but not overwritten

```
# $HESTIA/bin/v-add-firewall-ipset test-drop 'https://www.spamhaus.org/drop/drop.txt'

[root@:~]# head -n 10 $HESTIA/data/firewall/ipset/test-drop.v4.iplist
1.10.16.0/20
1.19.0.0/16
1.32.128.0/18
2.56.255.0/24
2.59.200.0/22
5.134.128.0/19
5.183.60.0/22
5.188.10.0/23
23.92.80.0/20
24.233.0.0/19

Can i delete **blacklist.sh** inside $HESTIA/data/firewall/ipset/  ?
```

**Comment by Lupul** [comment] 2020-08-02 12:14
glad you solved it, no need to remove the blacklist.sh file

**Comment by avcvv** [comment] 2020-08-02 12:38
i don't want use all service which exist in blacklist.sh, may i delete this file?

**Comment by jaapmarcus** [comment] 2020-08-02 13:58
blacklist.sh will be reset during next update...
Just don't activite in your control panel

**Comment by avcvv** [comment] 2020-08-02 14:01
> blacklist.sh will be reset during next update...
> Just don't activite in your control panel

Where in CP activate menu? i didn't see it

**Comment by jaapmarcus** [comment] 2020-08-02 14:07
Edit Server -> Firewall -> IPset it will show the installed list if installed.
