### ISSUE TITLE
sudo: no tty present and no askpass program specified

### ISSUE THREAD

**Issue by hrvylein** [hestiacp/hestiacp#204] opened 2019-03-13 12:40 UTC
Did a fresh install on Debian 9. Everything works right now but every action f.e. v-restore-user leads to an email with following contents:

> We trust you have received the usual lecture from the local System
> Administrator. It usually boils down to these three things:
> 
>     #1) Respect the privacy of others.
>     #2) Think before you type.
>     #3) With great power comes great responsibility.
> 
> sudo: no tty present and no askpass program specified

Additionally no system accounts for the created webusers are created.

**Comment by ScIT-Raphael** [comment] 2019-03-13 13:08
Just checked on a freshly installed Debian9:
```
root@web02:~# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.8 (stretch)
Release:        9.8
Codename:       stretch
```
Restored backup user, created accounts - can't repoduce your issue. It sounds like you've no sudoers file, it should be placed in /etc/sudoers.d/admin with the following content:
```
# Created by hestia installer
Defaults env_keep="VESTA"
Defaults env_keep+="HESTIA"
Defaults:admin !syslog
Defaults:admin !requiretty
Defaults:root !requiretty

# sudo is limited to hestia scripts
admin   ALL=NOPASSWD:/usr/local/vesta/bin/*
admin   ALL=NOPASSWD:/usr/local/hestia/bin/*
```
Because our test systems are working properly, I will close this issue. Please feel free to reopen it or create a new one.

**Closed as completed by ScIT-Raphael** 2019-03-13 13:08 UTC

**Comment by hrvylein** [comment] 2019-03-13 13:14
I already checked the sudoers file. It is there in /etc/sudoers.d/

```
root@srv:/etc/sudoers.d# ls -l
total 8
-r--r----- 1 root root 286 Mar 13 13:10 admin
-r--r----- 1 root root 958 Jun  5  2017 README
```

Content is

```
# Created by hestia installer
Defaults env_keep="VESTA"
Defaults env_keep+="HESTIA"
Defaults:admin !syslog
Defaults:admin !requiretty
Defaults:root !requiretty
 
# sudo is limited to hestia scripts
admin   ALL=NOPASSWD:/usr/local/vesta/bin/*
admin   ALL=NOPASSWD:/usr/local/hestia/bin/*
```


and this is the content of the sudoers file

```
#
# This file MUST be edited with the 'visudo' command as root.
#
# Please consider adding local content in /etc/sudoers.d/ instead of
# directly modifying this file.
#
# See the man page for details on how to write a sudoers file.
#
Defaults        env_reset
Defaults        mail_badpass
Defaults        secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
 
# Host alias specification

# User alias specification
 
# Cmnd alias specification
 
# User privilege specification
root    ALL=(ALL:ALL) ALL
 
# Allow members of group sudo to execute any command
%sudo   ALL=(ALL:ALL) ALL
 
# See sudoers(5) for more information on "#include" directives:
 
#includedir /etc/sudoers.d
```

Still I get an email every 5 minutes from failed cronjobs.

**Comment by Pleskan** [comment] 2019-03-13 13:18
@hrvylein check that you have **_bash_** shell for user named **admin**  in hestia settings

**Comment by ScIT-Raphael** [comment] 2019-03-13 13:26
@Pleskan I'm sorry but this has nothing to do with the shell access rights of admin. We removed them for security reasons.

@hrvylein Can you share more informations about your system (version and so on)? Maybe also about your hoster. I just checked it on two vm's, one is a vps at hetzner.de, second is a lxc container virtualized with proxmox - still can't reproduce your issue.

**Comment by hrvylein** [comment] 2019-03-13 13:43
Of course. It is an openvz container with kernel version Linux 2.6.32-042stab127.2.
```
lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.8 (stretch)
Release:        9.8
Codename:       stretch
```
I currently get mails for three failed cronjobs
```
sudo /usr/local/vesta/bin/v-update-sys-rrd
sudo /usr/local/vesta/bin/v-update-sys-queue backup
sudo /usr/local/vesta/bin/v-update-sys-queue letsencrypt
```
unfortunately there is no error in the hestia logs.

//Edit
Wait ... why is it calling the script in /usr/local/vesta? I reinstalled two user backups, coming from VestaCP.

**Comment by ScIT-Raphael** [comment] 2019-03-13 13:47
Could you try to install a Ubuntu Server 18.04 LTS and Hestia on top? Just to see if we've there the same issue. Meanwhile I will check with our team if someone had this issue already once.

**Comment by ScIT-Raphael** [comment] 2019-03-13 13:50
> sudo /usr/local/vesta/bin/v-update-sys-rrd
> sudo /usr/local/vesta/bin/v-update-sys-queue backup
> sudo /usr/local/vesta/bin/v-update-sys-queue letsencrypt
> //Edit
> Wait ... why is it calling the script in /usr/local/vesta? I reinstalled two user backups, coming from VestaCP.

Hmm, was this a fresh installed server? Or did you had removed and installed vesta?

**Comment by hrvylein** [comment] 2019-03-13 13:51
This is the result of `crontab -e` on `admin`
```
MAILTO=
CONTENT_TYPE="text/plain; charset=utf-8"
15 02 * * * sudo /usr/local/vesta/bin/v-update-sys-queue disk
10 00 * * * sudo /usr/local/vesta/bin/v-update-sys-queue traffic
30 03 * * * sudo /usr/local/vesta/bin/v-update-sys-queue webstats
*/5 * * * * sudo /usr/local/vesta/bin/v-update-sys-queue backup
10 05 * * * sudo /usr/local/vesta/bin/v-backup-users
20 00 * * * sudo /usr/local/vesta/bin/v-update-user-stats
*/5 * * * * sudo /usr/local/vesta/bin/v-update-sys-rrd
44 3 * * * sudo /usr/local/vesta/bin/v-update-sys-vesta-all
42 5 * * * sudo /usr/local/vesta/bin/v-update-letsencrypt-ssl
*/5 * * * * sudo /usr/local/vesta/bin/v-update-sys-queue letsencrypt
```
Could it be, that restoring the admin user (I store error and default pages on him) overwrote the crontab?

> Hmm, was this a fresh installed server? Or did you had removed and installed vesta?

Fresh install on debian 9. I restored two backups from vesta. One was the admin user.

**Comment by ScIT-Raphael** [comment] 2019-03-13 13:53
Ah, and admin restores you the cronjobs. u need to remove them. Usualy: Do not host anything under the admin user.

**Comment by ScIT-Raphael** [comment] 2019-03-13 14:39
Just did a commit to prevent this behaviour on beta branche: https://github.com/hestiacp/hestiacp/commit/c76d36016c35e56367b102c3c9738a0290e31ad8

**Comment by Roshini0307** [comment] 2022-07-19 10:21
Hi,

Could anyone help on this issue

Agent installation operation was not successful
Failed to install kit. Exit code: 1
Standard Output: Sudo path: /etc/opt/microsoft/scx/conf/sudodir/
Standard Error:
We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:
#1) Respect the privacy of others.
#2) Think before you type.
#3) With great power comes great responsibility.
sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
Exception Message:

**Comment by jaapmarcus** [comment] 2022-07-19 10:28
Your issue is not related to Hestia. We can't help with it

**Comment by divinity76** [comment] 2022-07-19 14:35
fwiw this sounds like a configuration issue with your SSH server or client. Assuming you use the OpenSSH client (which is the default ssh client in almost all Linux distros, and the default ssh client for WSL), connecting with `ssh -T user@ip` will reproduce the issue (for anyone, not just you). connecting with `ssh -t user@ip` should fix the issue. after you connect, running `script /dev/null`  before you invoke sudo/hestia commands, should also fix the issue.
