### ISSUE TITLE
[bug] dovecot not running

### ISSUE THREAD

**Issue by babulgogoi** [hestiacp/hestiacp#3482] opened 2023-04-20 05:10 UTC
### Describe the bug

error:
```root@host:/etc/dovecot/conf.d$ sudo systemctl status dovecot.service
× dovecot.service - Dovecot IMAP/POP3 email server
     Loaded: loaded (/lib/systemd/system/dovecot.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Thu 2023-04-20 10:23:05 IST; 3min 3s ago
       Docs: man:dovecot(1)
             https://doc.dovecot.org/
    Process: 1479892 ExecStart=/usr/sbin/dovecot -F (code=exited, status=89)
   Main PID: 1479892 (code=exited, status=89)
        CPU: 18ms

Apr 20 10:23:05 host.com systemd[1]: Starting Dovecot IMAP/POP3 email server...
Apr 20 10:23:05 host.com dovecot[1479892]: doveconf: Fatal: Error in configuration file /etc/dovecot/conf.d/10-ssl.conf line 6: ssl_cert: Can't open file /usr/>
Apr 20 10:23:05 host.com systemd[1]: dovecot.service: Main process exited, code=exited, status=89/n/a
Apr 20 10:23:05 host.com systemd[1]: dovecot.service: Failed with result 'exit-code'.
Apr 20 10:23:05 host.com systemd[1]: Failed to start Dovecot IMAP/POP3 email server.
```

10-ssl.conf:

```more 10-ssl.conf
ssl = yes
ssl_min_protocol = TLSv1.2
ssl_prefer_server_ciphers = yes
ssl_cipher_list = ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDH
E-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SH
A384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-A
ES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES
-CBC3-SHA:!DSS
ssl_cert = </usr/local/hestia/ssl/certificate.pem
ssl_key = </usr/local/hestia/ssl/certificate.key

# From and up to version 2.2
#ssl_dh_parameters_length = 4096

# From version 2.3
ssl_dh = </etc/ssl/dhparam.pem
```

ls -l:

```root@host:/usr/local/hestia/ssl$ ls -l
total 12
-rw-rw-r-- 1 Debian-exim mail 5975 Apr  7 16:26 certificate.crt
-rw-rw-r-- 1 Debian-exim mail 3272 Apr  7 16:26 certificate.key
```
i can read the .crt and .key files.
i see nothing wrong.

### Tell us how to replicate the bug

start or restart I get error on dovecote

### Which components are affected by this bug?

Mail (Exim, Dovecot)

### Hestia Control Panel Version

1.7.3 (amd64)

### Operating system

Ubuntu 22.04.2 LTS

### Log capture

```shell
error:
`root@host:/etc/dovecot/conf.d$ sudo systemctl status dovecot.service
× dovecot.service - Dovecot IMAP/POP3 email server
Loaded: loaded (/lib/systemd/system/dovecot.service; enabled; vendor preset: enabled)
Active: failed (Result: exit-code) since Thu 2023-04-20 10:23:05 IST; 3min 3s ago
Docs: man:dovecot(1)
https://doc.dovecot.org/
Process: 1479892 ExecStart=/usr/sbin/dovecot -F (code=exited, status=89)
Main PID: 1479892 (code=exited, status=89)
CPU: 18ms

Apr 20 10:23:05 host.com systemd[1]: Starting Dovecot IMAP/POP3 email server...
Apr 20 10:23:05 host.com dovecot[1479892]: doveconf: Fatal: Error in configuration file /etc/dovecot/conf.d/10-ssl.conf line 6: ssl_cert: Can't open file /usr/>
Apr 20 10:23:05 host.com systemd[1]: dovecot.service: Main process exited, code=exited, status=89/n/a
Apr 20 10:23:05 host.com systemd[1]: dovecot.service: Failed with result 'exit-code'.
Apr 20 10:23:05 host.com systemd[1]: Failed to start Dovecot IMAP/POP3 email server.
```

**Comment by jaapmarcus** [comment] 2023-04-20 05:34
Did you make any recent changes?

**Comment by babulgogoi** [comment] 2023-04-20 05:37
I just enabled php 7.4 in the system.

**Comment by jaapmarcus** [comment] 2023-04-20 06:22
Strange:
```
ssl = yes
ssl_min_protocol = TLSv1.2
ssl_prefer_server_ciphers = yes
ssl_cipher_list = ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS

ssl_cert = </usr/local/hestia/ssl/certificate.crt
ssl_key = </usr/local/hestia/ssl/certificate.key

# From and up to version 2.2
#ssl_dh_parameters_length = 4096

# From version 2.3
ssl_dh = </etc/ssl/dhparam.pem
```
Should be working fine on Ubuntu 22

What are the permissions of /usr/local/hestia/ssl and

**Comment by babulgogoi** [comment] 2023-04-20 06:30
![image](https://user-images.githubusercontent.com/14025503/233277179-6f3e5ec9-4618-42ef-860e-6233b71dfed9.png)
---
![image](https://user-images.githubusercontent.com/14025503/233277504-7775956c-7214-454a-9329-e7e15b19575d.png)

**Comment by jaapmarcus** [comment] 2023-04-20 08:44
And /usr/local/ 
And so on 

Maybe the issue is the missing enter between 

ssl_cipher_list = ....
and 
ssl_cert = </usr/local/hestia/ssl/certificate.crt

I have no idea other wise

**Comment by jaapmarcus** [comment] 2023-04-21 08:51
I will close the issue as it is not reproducible. Feel free to contact me on Discord so we can debug the issue

**Closed as completed by jaapmarcus** 2023-04-21 08:51 UTC
Labels: bug
