### ISSUE TITLE
Bug with same domain name

### ISSUE THREAD

**Issue by edica** [hestiacp/hestiacp#1030] opened 2020-07-29 19:44 UTC
### In a few words, please describe the issue that you're experiencing:
When added 2 or more domains with the same name, but with different extension.

Example:

namedomain.com
namedomain.com.br

### What steps did you take when the issue occured? 
1. Alias webmail. / mail. don’t work properly. It will always open with the last domain that was added.
2. Update of letsencrypt every 3 months of the error.

### Operating system:
Debian 10.4

### Hestia Control Panel version:
v1.2.1

### Additional notes:
You may have more related bugs when adding 2 domains with the same name. I haven't tested it completely.

**Comment by vestacp-user** [comment] 2020-07-29 20:59
Can you be more precise on which screen you have these two domains?  I imagine you created two "Web Domains" using the "Add Web Domain" button?

Do you want two completely different sites or the two sites are identical?

If they are identical, please use the "Aliases" field of the "Web Domain" and properly setup two differents DNS zones (and update the nameservers on the domains).  My guess would be that it is not configured correctly since these are two different TLD (Top Level Domains) that look like subdomains, but are not.  

Can you provide more details on your configuration and ideally screenshots?

**Comment by edica** [comment] 2020-07-30 16:51
Yes, two domains in "Web Domain" using the "Add Web Domain" button.
There are two domains with different content.

Both were in identical configuration, dns, mail ... And when I removed the domain that was working correctly, the other started to work perfectly.

Unfortunately I removed the 2 domains because it is not working properly.

**Comment by edica** [comment] 2020-07-31 13:18
It is important to know that there are also domain extensions: com.br (Brazil), com.mx (Mexico), com.ar (Argentina)....

I just found another problem (not so important). But to realize that there are mistakes when it comes to these types of extensions. When trying to add a domain in "Web Domains" domainname.com.br does not create the alias www. You must write manually.

**Comment by vestacp-user** [comment] 2020-08-01 01:05
The resolving of `namedomain.com` and `namedomain.com.br` is done by bind9 and the two are technically unrelated.  I have tried some similar variations and have not found any problems.

It is the TLD `.com` is authoritative for `namedomain.com`
It is the TLD `.br` that is authoritative for `com.br` which is in turn authoritative for `namedomain.com.br`

So first you have to make sure that both are looking to your HestiaCP server for name resolution.  

You must have a seperate a properly configured "DNS Zone" in Hestia for `namedomain.com` AND `namedomain.com.br` because you certainly do NOT control `com.br`  If you were configuring proper subdomains, then you could do it in one zone or two seperate ones with proper configuration in the second level domain zone pointing to the thirsd level domain.

As for the 'Web Domain', two seperate for two seperate site or one with alias for identical sites will both work ok. I have tested with chains of subdomains, and the only part that Hestia does not automate (and rightly so) is linking the subdomain  "DNS Zone" to the parent  "DNS Zone" if it exists.  This is the behavior of Bind9 probably to protect against non-authoritative nameserver hijacking in a shared server environment (same IP).  So the Hestia user simply has to put `subdomain.example.com` in the "DNS Zones" of `example.com` to ensure the proper authoritative name resolution. 

As for `www.` prefix, this is just a convenience provided by Hestia and there are no rules, requirements or protocol for it even on second level domains, even less so for third level domains.  I think it will probably remain manual for subdomains, but I will let the Hestia team decide.

My guess would be that you will have to provide a step-by-step precise example that can be reproduced for each of the problems you describe if you want them to be further analyses for potential bugs in Hestia.

**Comment by jaapmarcus** [comment] 2020-08-01 08:35
Hello edica 

Tried to replicate the issue on my "test" server but had no success. 

Could you please give me some information on the steps taken how we can replicate the issue?

**Comment by edica** [comment] 2020-08-06 13:10
Unfortunately I no longer have access to the 2 domains I was working on.
The error with letsencrypt updating every 3 months already gave an error in Vesta. The error was always with ".com.br"
But maybe I was doing something wrong with the configuration in CloudFlare.

About the Alias.
1. Click Add Web Domains.
2. In the Domain add for example: domain.com.br
3. Click on "Advanced Options"
Should the Aliases automatically fill **www**.domain.com.br?

Sorry my english.
Thanks.

**Comment by ScIT-Raphael** [comment] 2020-08-06 13:13
Infact we can't replicate the issue, I gonna close it for now. Please feel free to reopen it, if it should occure again.

**Closed as completed by ScIT-Raphael** 2020-08-06 13:13 UTC
Labels: web

**Comment by jaapmarcus** [comment] 2020-08-06 13:34
> About the Alias.
> 
> 1. Click Add Web Domains.
> 2. In the Domain add for example: domain.com.br
> 3. Click on "Advanced Options"
>    Should the Aliases automatically fill **www**.domain.com.br?
> 

Know issue but on the other hard to to fix due to domains like .co.uk, com.mx ect... Don't know if there is a easy fix for it. Expect creating a list with all the exceptions...
