### ISSUE TITLE
Iptables greyed out on new install of hestiacp 1.2 Ubuntu LXC

### ISSUE THREAD

**Issue by johnnyq** [hestiacp/hestiacp#884] opened 2020-06-29 17:40 UTC
**Please include as much information as possible in your issue report, such as the configuration of your server and any troubleshooting steps that you've already performed.**

**NOTE: Do not include any personal or sensitive information, such as email addresses or passwords.**

===

### In a few words, please describe the issue that you're experiencing:
I noticed iptables is grayed out on a new install of hestiacp 1.2 with ubuntu 20.04 lxc template (Proxmox)

### What steps did you take when the issue occured? 
1. Install hestia
2. Check Services

### Expected behavior:
Iptables should not be grayed out

### Operating system:
ubuntu 20.04 LXC Template (Proxmox)

### Hestia Control Panel version:
1.2.0 default install

**Comment by ScIT-Raphael** [comment] 2020-06-29 17:43
There is known issue with lxc install, we currently remove 1.2.0 from the repository and do deeper testings.

**Comment by vr0** [comment] 2020-06-29 18:42
Same on Ubuntu 20.04 Server without LXC etc.

The problem based more on the "predefined" iptables paths:

```
v-add-firewall-chain
v-delete-firewall-ban
v-delete-firewall-chain
v-list-sys-services
v-stop-firewall
v-update-firewall

# Defining absolute path for iptables and modprobe
iptables="/sbin/iptables"
...
/sbin/iptables-save > /etc/sysconfig/iptables
/sbin/iptables-save > /etc/iptables.rules
...
echo '    /sbin/iptables-restore < /etc/iptables.rules' >> $preup
echo "/sbin/iptables-restore < /etc/iptables.rules" >> $preup

etc..
```

> Ubuntu 18.04 default path: /sbin/iptables*
> Ubuntu 20.04 default path: /usr/sbin/iptables*

Yes you can do symlinks as workaround.. (iptables works but still greyed out)

```
ln -s $(which iptables) /sbin/iptables
ln -s $(which iptables-save) /sbin/iptables-save
ln -s $(which iptables-restore) /sbin/iptables-restore
```
Or using sed... (iptables works but still greyed out)

```
cd $HESTIA/bin
sed -i 's:/sbin/iptables:/usr/sbin/iptables:g' *
```

But that's not the right way..

Cheers.

**Comment by ScIT-Raphael** [comment] 2020-06-29 18:58
Hi @vr0 

Thanks for providing use additional informations, we've removed the 1.2.0 release and reworking the related part. You're input will help us to properly solve the issue, once again, thank you!

**Comment by Lupul** [comment] 2020-06-29 20:13
@vr0 in our tests ubuntu 20.04 did come with symlinks for /sbin/iptables, and only sistem upgraded from 18.04 to 20.04 were missing them. Was you system upgraded from u18.04?

To handle this we are checking for missing symlinks during upgrade: https://github.com/hestiacp/hestiacp/commit/61a88dba46586cc8b5c2447e458b38545240b858 but this needs to happen in the installer also.

**Comment by vr0** [comment] 2020-06-29 21:10
Yes,
upgrade from Ubuntu 18.04 --> 20.04. (Because HestiaCP 1.2.0 support now Ubuntu 20.04)

Cheers.

**Comment by ScIT-Raphael** [comment] 2020-06-30 14:51
According to https://github.com/hestiacp/hestiacp/issues/883#issuecomment-651844059, the issue is fixed with the following commit: https://github.com/hestiacp/hestiacp/commit/68b6741a1bb6004ab171a039dbe386c9710ec604

**Closed as completed by ScIT-Raphael** 2020-06-30 14:51 UTC
Labels: bug, interface
