### ISSUE TITLE
[Bug] Setting up proxy_pass on the main hostname domain

### ISSUE THREAD

**Issue by Karman40** [hestiacp/hestiacp#4315] opened 2024-03-03 13:17 UTC
### Describe the bug

I would like to set up a proxy_pass for the main hostname domain to hide the port number from the domain. I have configured it accordingly, but for some reason, when the admin panel loads, it automatically redirects to the specified port number.

### Tell us how to replicate the bug

```
#=========================================================================#
# Default Web Domain Template                                             #
# DO NOT MODIFY THIS FILE! CHANGES WILL BE LOST WHEN REBUILDING DOMAINS   #
# https://hestiacp.com/docs/server-administration/web-templates.html      #
#=========================================================================#

server {
        listen      %ip%:%proxy_port%;
        server_name %domain_idn% %alias_idn%;
        error_log   /var/log/%web_system%/domains/%domain%.error.log error;

        include %home%/%user%/conf/web/%domain%/nginx.forcessl.conf*;

        location ~ /\.(?!well-known\/|file) {
                deny all;
                return 404;
        }

        location / {
                proxy_pass         http://localhost:8083/;
                proxy_set_header   X-Real-IP $remote_addr;
                proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header   Host $host;
                proxy_http_version 1.1;
                # proxy_set_header   Upgrade $http_upgrade;
                # proxy_set_header   Connection "upgrade";
        }

        include %home%/%user%/conf/web/%domain%/nginx.conf_*;
}
```

### Which components are affected by this bug?

Control Panel Backend, Control Panel Web Interface

### Hestia Control Panel Version

v1.8.11

### Operating system

Ubuntu 22.04 LTS

**Comment by jaapmarcus** [comment] 2024-03-03 16:19
Use http:// instead of    http://

As this is not a bug / feature request I will close the issue

See:

https://github.com/jaapmarcus/web-templates/blob/master/templates/nginx/cp.stpl
and 
https://github.com/jaapmarcus/web-templates/blob/master/templates/nginx/cp.tpl

**Closed as completed by jaapmarcus** 2024-03-03 16:19 UTC
Labels: bug
