### ISSUE TITLE
Rebuilding domains makes the websites to fail with "X redirected you too many times."

### ISSUE THREAD

**Issue by gdarko** [hestiacp/hestiacp#1199] opened 2020-09-17 15:35 UTC
I selected multiple websites and clicked "Rebuild All" and now there seem to be redirect loop on all those domains

Operating System: Debian 10

**Comment by ScIT-Raphael** [comment] 2020-09-20 16:56
Hi @gdarko 

Sorry for the late reply, but you didnt provided us a lot of informations, aswell as removed the whole issue template which isnt decoration :).

Usualy, the redirect comes from somewhere like .htaccess or the http-to-https redirect. If you get a loop, you'll need to find out where it happens, the written rebuild process does recreate every conf file and will also be triggered during the hestia update process. So if you have already installed a hestia update on that server, it would lead me that the issue isnt related to the rebuild itself.

I'll close the issue report for now due to the lack of information. Please feel free to provide them in the existing (edit) or a new issue report.

**Closed as completed by ScIT-Raphael** 2020-09-20 16:56 UTC
