### ISSUE TITLE
Problem when restoring backup

### ISSUE THREAD

**Issue by liamgibbins** [hestiacp/hestiacp#1361] opened 2020-11-10 13:27 UTC
1. When restoring a backup the backup folder is not automatically created when you install Hestiacp.
You have to create the directory first.
2. The user is not created you have to create the user in the panel before restoring a backup.
3.  SSL Certificates are not copied from the backup it throws errors while backing up both on domain and email.
4. On occasion when restoring it will not restore a domain just says directory/file does not exist
===

### In a few words, please describe the issue that you're experiencing:
1. When restoring a backup the backup folder is not automatically created when you install Hestiacp.
You have to create the directory first.
2. The user is not created you have to create the user in the panel before restoring a backup.
3.  SSL Certificates are not copied from the backup it throws errors while backing up both on domain and email.

### What steps did you take when the issue occured? 
Create backup folder and upload backup
Use the restore backup CLI command

**To fix this (work around):**
To make backups restore:
  Create a backup folder
  Create user in the panel
  Run Back up. (if it says file/directory not exist then create the domain in the panel)
  In the domains panel click SSL and Letsencrypt and click save
Now SSL is enabled on the Domain.
  In the mail panel click SSL but dont click letsencrypt and click save
  Now unclick SSL and click save
  Then Click SSL and letsencrypt and click save
Now ssl should be installed for email

### Expected behavior:
Upload Backup and use restore cli and it should restore

### Operating system:
Debain 10.6

### Hestia Control Panel version:
Version 1.3.0

### Additional:
Some times you will have issue connecting to the smtp server simply deselect the ssl and enable it afew times and it will eventually work.

**Comment by jaapmarcus** [comment] 2020-11-10 13:45
- The user is not created you have to create the user in the panel before restoring a backup.
See: https://github.com/hestiacp/hestiacp/issues/1321 

Fixed will be released soon... 

For the other issue please provide use with log files.

**Comment by jeazyee** [comment] 2020-11-10 22:07
I have the same problem but only with SSL on MAIL here is the log:

`-- WEB --
2020-11-10 22:20:10 xxx.domain.com
2020-11-10 22:20:15 yyy.domain.com

-- DNS --
2020-11-10 22:20:17 domain.com

-- MAIL --
2020-11-10 22:20:17 domain.com
chmod: cannot access '/usr/local/hestia/data/users/username/ssl/mail.domain.com.*': No such file or directory
cp: cannot stat '/usr/local/hestia/data/users/username/ssl/mail.domain.com.crt': No such file or directory
cp: cannot stat '/usr/local/hestia/data/users/username/ssl/mail.domain.com.key': No such file or directory
cp: cannot stat '/usr/local/hestia/data/users/username/ssl/mail.domain.com.pem': No such file or directory
chmod: cannot access '/home/username/conf/mail/domain.com/ssl/*': No such file or directory
chown: cannot access '/home/username/conf/mail/domain.com/ssl/*': No such file or directory
chmod: cannot operate on dangling symlink '/usr/local/hestia/ssl/mail/mail.domain.com.crt'
chmod: cannot operate on dangling symlink '/usr/local/hestia/ssl/mail/mail.domain.com.key'

-- DB --
2020-11-10 22:20:20 username_social
/backup/tmp.um73QD5sNz/db/username_social/username_social.mysql.sql.zst: 87771951 bytes 
2020-11-10 22:20:30 username_sp
/backup/tmp.um73QD5sNz/db/username_sp/username_sp.mysql.sql.zst: 39709 bytes       

-- CRON --
2020-11-10 22:20:30 3 cron jobs

-- USER FILES --
2020-11-10 22:20:30 .bashrc
2020-11-10 22:20:30 .ssh
2020-11-10 22:20:30 .bash_logout
2020-11-10 22:20:30 .profile
2020-11-10 22:20:31 .local
2020-11-10 22:20:31 .npm
2020-11-10 22:20:31 .config
2020-11-10 22:20:31 .composer
2020-11-10 22:20:31 .cache
`

**Comment by jaapmarcus** [comment] 2020-11-13 13:19
This is creating a backup? or restoring an VestaCP backup?

**Comment by liamgibbins** [comment] 2020-11-13 13:41
Restoring a hestiacp backup not vestacp..
Basically I backed up reinstalled server (hestiacp) and restored backup.

**Comment by jaapmarcus** [comment] 2020-11-13 14:05
If possible please supply us with a back up without personal data but with the issue. So we can test it for our self on our servers.

**Also we have release an prerelease for 1.3.1 see https://forum.hestiacp.com/t/hestiacp-1-3-1-rc/2072/5 or Discord for how to install it**

**Comment by cmstew** [comment] 2020-11-16 05:18
I have seen the mail SSL error before too. I'll see if I can reproduce it.

**Comment by jaapmarcus** [comment] 2020-11-17 08:57
We have released 1.3.1 if the issue is still there please report them...

**Comment by jaapmarcus** [comment] 2020-12-16 12:06
Just check with an 1.3.2 backup and I am not able to reproduce it. 

We also have integrated automated testing for backup / restore function

If some body is able to repoduce the issue please supply us with an backup so we are able to reproduce the issue(s) on our own test systems.

**Closed as completed by jaapmarcus** 2020-12-16 12:06 UTC
