### ISSUE TITLE
[Bug] Task Monitor graphic charts stopped drawing after reboot

### ISSUE THREAD

**Issue by fuzhyperblue** [hestiacp/hestiacp#3970] opened 2023-08-30 19:39 UTC
### Describe the bug

Task Monitor graphic charts stopped drawing after reboot

### Tell us how to replicate the bug

1. reboot the server
2. chart stopped drawing
3. reboot the server again
4. chart still not drawing
5. reboot several times more
6. no positive result

<img width="1057" alt="Screenshot 2023-08-30 at 17 00 04" src="https://github.com/hestiacp/hestiacp/assets/36069041/f7e0519f-2339-487a-80c9-a9b6e730c870">

<img width="752" alt="Screenshot 2023-08-30 at 22 37 50" src="https://github.com/hestiacp/hestiacp/assets/36069041/aa42e972-6380-46c3-ab8a-164f7632d02b">

### Which components are affected by this bug?

Control Panel Web Interface

### Hestia Control Panel Version

1.8.7

### Operating system

Ubıuntu 22.04

**Comment by jaapmarcus** [comment] 2023-08-30 23:33
Can please share v-export-rrd la

We use the RDD tools have seen it not working for the first part in the past.. 

<img width="1048" alt="Screenshot 2023-08-31 at 01 33 18" src="https://github.com/hestiacp/hestiacp/assets/9754650/93b05a92-074f-4724-a7e6-12f70ff7f42a">


The only thing I can think of it that the RDD database are not updating any more

**Comment by fuzhyperblue** [comment] 2023-08-31 07:11
So the chart started drawing again, by itself, I did nothing.

![Screenshot 2023-08-31 100604](https://github.com/hestiacp/hestiacp/assets/36069041/9581dd7f-11bc-45c2-bbde-b802a71cb146)


but here is the output of said command:

```
{ "about": "RRDtool graph JSON output",
  "meta": {
    "start": 1693379400,
    "end": 1693465800,
    "step": 300,
    "legend": [
      "Load",
      "Processes"
          ]
     },
  "data": [
    [ 2.5045320080e+01, 1.9898489331e+02 ],
    [ 5.4806656600e+01, 1.9999355522e+02 ],
    [ 3.8119350710e+01, 1.9702106189e+02 ],
    [ 1.7154075180e+01, 2.0097065235e+02 ],
    [ 1.8989594073e+01, 1.9304162371e+02 ],
    [ 1.2052248023e+01, 2.0391789596e+02 ],
    [ 1.1006173950e+01, 1.9604939160e+02 ],
    [ 2.3932922990e+01, 2.0097420115e+02 ],
    [ 2.6979824480e+01, 1.9901345035e+02 ],
    [ 1.6057585770e+01, 1.9701047014e+02 ],
    [ 2.2969260713e+01, 2.0098243469e+02 ],
    [ 2.7965367617e+01, 1.9702770591e+02 ],
    [ 2.2034043020e+01, 1.9501134767e+02 ],
    [ 1.5051712150e+01, 1.9897045020e+02 ],
    [ 1.6987367580e+01, 1.9999368379e+02 ],
    [ 1.4020162080e+01, 2.0198655861e+02 ],
    [ 1.7980739813e+01, 2.0000963009e+02 ],
    [ 8.0595499333e+00, 1.9403572996e+02 ],
    [ 1.3962191880e+01, 2.0194958917e+02 ],
    [ 2.1953959707e+01, 1.9901726511e+02 ],
    [ 2.6973057533e+01, 1.9900000000e+02 ],
    [ 2.3029686040e+01, 1.9999257849e+02 ],
    [ 2.2008269403e+01, 1.9603307761e+02 ],
    [ 1.3055656960e+01, 1.9600000000e+02 ],
    [ 2.8890121973e+01, 1.9997253049e+02 ],
    [ 1.9065912600e+01, 1.9403954756e+02 ],
    [ 1.7015352833e+01, 1.9995394150e+02 ],
    [ 2.1975757750e+01, 1.9601939380e+02 ],
    [ 1.2064172833e+01, 2.0295507902e+02 ],
    [ 1.6964361350e+01, 2.0200712773e+02 ],
    [ 1.7000000000e+01, 2.0200000000e+02 ],
    [ 4.0816309680e+01, 2.0200000000e+02 ],
    [ 2.7112813773e+01, 2.0001611625e+02 ],
    [ 1.6063361687e+01, 1.9602304061e+02 ],
    [ 2.0969609333e+01, 2.0494529680e+02 ],
    [ 2.1000000000e+01, 1.9505987513e+02 ],
    [ 2.0005202207e+01, 2.0196358455e+02 ],
    [ 1.4036557580e+01, 1.9603655758e+02 ],
    [ 3.8807855500e+01, 2.0393851376e+02 ],
    [ 3.2043423963e+01, 1.9903101712e+02 ],
    [ 1.8104932800e+01, 1.9999250480e+02 ],
    [ 1.1035945770e+01, 1.9602054044e+02 ],
    [ 9.0106089800e+00, 2.0196817306e+02 ],
    [ 1.8924660533e+01, 2.0200000000e+02 ],
    [ 3.0929543320e+01, 2.0697064305e+02 ],
    [ 2.3052648640e+01, 2.0203290540e+02 ],
    [ 2.1010392000e+01, 1.9802078400e+02 ],
    [ 3.0953049733e+01, 2.0098591492e+02 ],
    [ 3.5966382283e+01, 2.0397982937e+02 ],
    [ 3.3018370540e+01, 1.9903061757e+02 ],
    [ 2.6039801837e+01, 1.9601705793e+02 ],
    [ 1.7046944570e+01, 2.0296348756e+02 ],
    [ 2.1976586250e+01, 2.0001404825e+02 ],
    [ 2.5974343733e+01, 1.9701924220e+02 ],
    [ 2.5006722673e+01, 2.0693277327e+02 ],
    [ 5.2856976280e+01, 1.9605618789e+02 ],
    [ 3.0174783133e+01, 1.9798480147e+02 ],
    [ 2.7015061930e+01, 2.0197991743e+02 ],
    [ 2.7000000000e+01, 2.0200000000e+02 ],
    [ 1.9040176453e+01, 2.0100502206e+02 ],
    [ 1.7014428867e+01, 1.9802164330e+02 ],
    [ 1.6005433640e+01, 2.0396739816e+02 ],
    [ 1.0045099240e+01, 2.0598496692e+02 ],
    [ 7.5064266667e+00, 1.5463238933e+02 ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ null, null ],
    [ 1.5936000000e+01, 2.0418000000e+02 ],
    [ 1.6029636000e+01, 2.0537971125e+02 ],
    [ 1.4013794447e+01, 2.0202069167e+02 ],
    [ 1.4993879400e+01, 2.0100612060e+02 ],
    [ 6.0622142100e+00, 1.9802073807e+02 ],
    [ 1.1953220540e+01, 1.9899220342e+02 ],
    [ 1.9957370560e+01, 1.9999467132e+02 ],
    [ 1.4027909660e+01, 1.9701395483e+02 ],
    [ 1.0020234040e+01, 2.0197470745e+02 ],
    [ 2.3910037150e+02, 2.0398355300e+02 ],
    [ 1.1092596346e+02, 2.0499293158e+02 ],
    [ 4.5484238733e+01, 2.0698510035e+02 ],
    [ 4.1022617253e+01, 2.0700000000e+02 ],
    [ 4.0006585607e+01, 2.0700000000e+02 ],
    [ 4.0000000000e+01, 2.1097041005e+02 ],
    [ 4.0992133323e+01, 1.9413373350e+02 ],
    [ 2.5128734560e+01, 1.9796781636e+02 ],
    [ 1.4062834713e+01, 2.0197715101e+02 ],
    [ 1.4992738437e+01, 2.0497821531e+02 ],
    [ 1.4006401130e+01, 2.0301280226e+02 ],
    [ 1.0022800080e+01, 1.9902280008e+02 ],
    [ 3.0858037270e+01, 2.0197971961e+02 ],
    [ 1.7071208200e+01, 2.0498474110e+02 ],
    [ 3.0907055260e+01, 2.0003319455e+02 ],
    [ 2.4061391633e+01, 2.0198245953e+02 ],
    [ 1.9038161950e+01, 2.0696183805e+02 ],
    [ 1.9994121610e+01, 2.0103527034e+02 ],
    [ 2.1986298967e+01, 1.9901370103e+02 ],
    [ 1.3047853930e+01, 1.9601595131e+02 ],
    [ 9.0250016133e+00, 1.9997499839e+02 ],
    [ 9.0000000000e+00, 2.0198899501e+02 ],
    [ 9.9925642900e+00, 2.0100743571e+02 ],
    [ 1.7959452827e+01, 2.0398479481e+02 ],
    [ 1.4024230880e+01, 2.0201211544e+02 ],
    [ 1.4992947167e+01, 1.9604231700e+02 ],
    [ 1.4004974363e+01, 1.9998010255e+02 ],
    [ 1.3006440043e+01, 1.9801288009e+02 ],
    [ 2.2922147567e+01, 1.9998442951e+02 ],
    [ 2.7964035367e+01, 1.9900719293e+02 ],
    [ 2.0045348720e+01, 1.9502267436e+02 ],
    [ 9.0860813433e+00, 2.0095304654e+02 ],
    [ 1.7945341950e+01, 1.9404251182e+02 ],
    [ 1.8994850467e+01, 2.0494335513e+02 ],
    [ 3.7880413557e+01, 2.0599370598e+02 ],
    [ 4.1971082107e+01, 2.0302168842e+02 ],
    [ 2.5124923933e+01, 1.9406613620e+02 ],
    [ 1.2066064483e+01, 1.9797967247e+02 ],
    [ 2.5911010493e+01, 1.9203813836e+02 ],
    [ 1.8041433360e+01, 1.9697410415e+02 ],
    [ 1.8000000000e+01, 1.9501328681e+02 ],
    [ 8.0612867333e+00, 2.1388355521e+02 ],
    [ 2.7833425533e+01, 1.9714158830e+02 ],
    [ 3.8921442547e+01, 2.0395000889e+02 ],
    [ 3.6016971370e+01, 1.9604525699e+02 ],
    [ 3.6994442600e+01, 1.9500555740e+02 ],
    [ 3.1030261800e+01, 1.9897982547e+02 ],
    [ 2.1069187300e+01, 2.0197924381e+02 ],
    [ 3.3888523007e+01, 1.9605145092e+02 ],
    [ 3.4000000000e+01, 2.0394694064e+02 ],
    [ 1.4124748867e+01, 1.9803742466e+02 ],
    [ 1.5985774840e+01, 1.9800000000e+02 ],
    [ 1.6995817203e+01, 1.9899581720e+02 ],
    [ 3.2912170027e+01, 2.0496706376e+02 ],
    [ 3.1013482667e+01, 1.9606067200e+02 ],
    [ 4.4913169620e+01, 2.0196278698e+02 ],
    [ 6.8867394240e+01, 2.0299447476e+02 ],
    [ 3.4282360400e+01, 1.9407260696e+02 ],
    [ 3.4000000000e+01, 1.9697542171e+02 ],
    [ null, null ]
  ]
```

**Comment by jaapmarcus** [comment] 2023-08-31 08:14
Mostlikly the RDD database was corrupted some how... Mainly caused by the reboot. Probably impossible to fix It from our side...

Will close the issue

**Closed as completed by jaapmarcus** 2023-08-31 08:14 UTC
Labels: bug
