### ISSUE TITLE
Not getting real client ip address

### ISSUE THREAD

**Issue by alber-khan** [hestiacp/hestiacp#652] opened 2019-12-17 10:32 UTC
### In a few words, please describe the issue that you're experiencing:

i'm not getting real client ip address in php
<?php echo $_SERVER['REMOTE_ADDR']; ?>

### What steps did you take when the issue occured? 

![image](https://user-images.githubusercontent.com/39749258/70987419-e03e4b80-20e5-11ea-8212-0376f5ab5807.png)

i realised remoteip.conf didn't got installed so i need to manually create a file and upload it to 

/etc/apache2/mods-available - remoteip.conf

< IfModule mod_remoteip.c>
   RemoteIPHeader X-Forwarded-For
   RemoteIPHeader X-Real-IP
   RemoteIPInternalProxy 127.0.0.1 ::1 your-server-ip
</ IfModule>

### Expected behavior:
Should forward real client ip address to apache2 

### Operating system distribution and release:
Ubuntu 18.04.2

### Which version of Hestia Control Panel is currently installed?
1.0.6

### Which branch are you using?
release

### When did this issue occur? After a clean installation, or after an upgrade?
clean installation

### Which of the following web server configurations are you using?
- Apache + Nginx (default)
- Multi-PHP

### Which of the following server roles are installed on your server?
- DNS
- Mail (Dovecot + Exim)
- MySQL (MariaDB)

**Comment by Lupul** [comment] 2019-12-17 12:31
Duplicate of #633

**Closed as completed** 2019-12-17 12:32 UTC
