### ISSUE TITLE
Apache and Nginx, both as default?

### ISSUE THREAD

**Issue by guettli** [hestiacp/hestiacp#1514] opened 2020-12-30 08:38 UTC
https://docs.hestiacp.com/getting_started.html

> -a, --apache          Install Apache        [yes|no]  default: yes
> 
> -n, --nginx           Install Nginx         [yes|no]  default: yes

I think it does not make sense that both are enabled by default.

I think it is ok to if hestiacp is opinionated here and prefers one webserver.

**Comment by ScIT-Raphael** [comment] 2020-12-30 08:43
That's the way hestia works, it runs nginx in front of apache2 to speed up as caching proxy before forwarding then to apache2. Only nginx is running on 80/443, spache2 is running on 8080/8443. Try it out and you see what I mean :).

Feature, not a bug- so I'll close the issue. Please stick over to our forum or discord channel for any feature requests.

**Closed as completed by ScIT-Raphael** 2020-12-30 08:43 UTC
