### ISSUE TITLE
Webmail not working with Cloudflare

### ISSUE THREAD

**Issue by avcvv** [hestiacp/hestiacp#1356] opened 2020-11-09 08:37 UTC
**Please include as much information as possible in your issue report, such as the configuration of your server and any troubleshooting steps that you've already performed.**

**NOTE: Do not include any personal or sensitive information, such as email addresses or passwords.**

===

### In a few words, please describe the issue that you're experiencing:

I'm using Cloudflare and tried according manual deploy webmail, but how can i see right now my server only accept emails, i can't open roundcube. When i try to visit webmail (roundcube) i see only (Success!
Your new web server is ready to use.)

I tried many time rebuild web+mail it didn't help, main domain using cf ssl. This happened only with domains which pointed to CF.

<img width="1132" alt="DNS" src="https://user-images.githubusercontent.com/39009179/98517881-aaff9680-227f-11eb-8d5d-d0ae46305525.png">
<img width="754" alt="Success! 2020-11-09 11-34-08" src="https://user-images.githubusercontent.com/39009179/98517892-adfa8700-227f-11eb-991a-8aec5f15e814.png">

### What steps did you take when the issue occured? 
1. Ex.: Click on the "Web" tab.
2. Ex.: Click on "Add Web Domain".
3. Ex.: Attempted to add a domain and received an Internal Server Error.

### Expected behavior:
Please enter your answer here (e.g. the web domain should have been added successfully).

### Operating system:
Ubuntu 20.04 LTS
### Hestia Control Panel version:
Last version 

### Additional notes:
If there is anything else that you'd like us to know about this issue that will help us diagnose and troubleshoot more effectively, such as links to forum posts or other discussions, please feel free to share here.

**Comment by avcvv** [comment] 2020-11-09 08:45
Right now stopped working all email domain, even not CF

`root@pzdc:~# systemctl status dovecot
● dovecot.service - Dovecot IMAP/POP3 email server
     Loaded: loaded (/lib/systemd/system/dovecot.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2020-11-09 09:43:00 CET; 2min 18s ago
       Docs: man:dovecot(1)
             http://wiki2.dovecot.org/
    Process: 1783165 ExecReload=/usr/bin/doveadm reload (code=exited, status=0/SUCCESS)
   Main PID: 1781740 (dovecot)
      Tasks: 3 (limit: 19116)
     Memory: 4.2M
     CGroup: /system.slice/dovecot.service
             ├─1781740 /usr/sbin/dovecot -F
             ├─1781752 dovecot/anvil
             └─1783188 dovecot/log

Nov 09 09:43:00 pzdc.fun systemd[1]: Started Dovecot IMAP/POP3 email server.
Nov 09 09:43:00 pzdc.fun dovecot[1781740]: doveconf: Warning: NOTE: You can get a new clean config file with: doveconf -Pn > dovecot-new.conf
Nov 09 09:43:00 pzdc.fun dovecot[1781740]: doveconf: Warning: Obsolete setting in /etc/dovecot/conf.d/10-ssl.conf:2: ssl_protocols has been replaced by ssl_min_protocol
Nov 09 09:43:00 pzdc.fun dovecot[1781740]: doveconf: Warning: Obsolete setting in /etc/dovecot/conf.d/10-ssl.conf:10: ssl_dh_parameters_length is no longer needed
Nov 09 09:45:13 pzdc.fun systemd[1]: Reloading Dovecot IMAP/POP3 email server.
Nov 09 09:45:13 pzdc.fun systemd[1]: Reloaded Dovecot IMAP/POP3 email server.
root@pzdc:~# systemctl status exim4
● exim4.service - LSB: exim Mail Transport Agent
     Loaded: loaded (/etc/init.d/exim4; generated)
     Active: active (running) since Mon 2020-11-09 09:43:29 CET; 1min 50s ago
       Docs: man:systemd-sysv-generator(8)
    Process: 1781886 ExecStart=/etc/init.d/exim4 start (code=exited, status=0/SUCCESS)
    Process: 1782901 ExecReload=/etc/init.d/exim4 reload (code=exited, status=0/SUCCESS)
      Tasks: 6 (limit: 19116)
     Memory: 157.4M
     CGroup: /system.slice/exim4.service
             ├─1779514 /usr/sbin/exim4 -bd -q30m
             ├─1780389 /usr/sbin/exim4 -bd -q30m
             ├─1781762 /usr/sbin/exim4 -bd -q30m
             ├─1782137 /usr/sbin/exim4 -bd -q30m
             ├─1782859 /usr/sbin/exim4 -bd -q30m
             └─1782878 /usr/sbin/exim4 -bd -q30m

Nov 09 09:43:29 pzdc.fun systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Nov 09 09:43:29 pzdc.fun systemd[1]: exim4.service: Found left-over process 1781877 (exim4) in control group while starting unit. Ignoring.
Nov 09 09:43:29 pzdc.fun systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Nov 09 09:43:29 pzdc.fun systemd[1]: Starting LSB: exim Mail Transport Agent...
Nov 09 09:43:29 pzdc.fun exim4[1781886]:    ...done.
Nov 09 09:43:29 pzdc.fun systemd[1]: Started LSB: exim Mail Transport Agent.
Nov 09 09:45:13 pzdc.fun systemd[1]: Reloading LSB: exim Mail Transport Agent.
Nov 09 09:45:13 pzdc.fun exim4[1782901]:  * Reloading exim4 configuration files
Nov 09 09:45:13 pzdc.fun exim4[1782901]:    ...done.
Nov 09 09:45:13 pzdc.fun systemd[1]: Reloaded LSB: exim Mail Transport Agent.`

**Comment by ScIT-Raphael** [comment] 2020-11-09 08:51
Define what exactly stopped working and what you did at last - usualy nothing is failing without any change. Also is only webmail failing or also the mail communication services itself?

Without additional and detailed informations, it's hard to help. Please switch to our discord server, it makes the communication easier: https://discord.gg/nXRUZch

Infact this is a local issue and nothing we can reproduce, I'll close this issue. We will be here to help on our discord channel (or forum).

**Comment by jaapmarcus** [comment] 2020-11-09 08:51
If you check you will see a warning before your mx records.

Disable for mail A xxxx Cloudflare proxy

**Closed as completed by ScIT-Raphael** 2020-11-09 08:51 UTC

**Comment by avcvv** [comment] 2020-11-09 08:53
This is not helped I can’t go to round cube

**Comment by ScIT-Raphael** [comment] 2020-11-09 08:54
But it will restore your mail services, because cloudflare doesnt allow proxy communciation over mail ports. As written, please stick over to discord.
