### ISSUE TITLE
[Bug] Restoring POSTGRES dbs from a backup assigns them ot the 'postgres' root user

### ISSUE THREAD

**Issue by d41ly** [hestiacp/hestiacp#3787] opened 2023-07-16 07:38 UTC
### Describe the bug

I've backed up an entire user account on one node, and moved the backup to another node. Using v-restore-user I restored the user, however, upon closer examination I've noticed that all the POSTGRES databases had their table (all db content) ownership assigned to 'postgres', which prevents the use of the table with any user other than the root.  During restore the log output said that "database user did not include a password, make sure to set a user password after" if that matters. 

### Tell us how to replicate the bug

1. Restore a full user backup
2. Take a look at any postgres db
3. See who's the owner of the tables
4. Cry a bit inside

### Which components are affected by this bug?

Database (MariaDB, MySQL, PostgreSQL)

### Hestia Control Panel Version

1.8.1

### Operating system

Ubuntu 22.04

**Comment by istiak101** [comment] 2023-07-26 01:13
Duplicate of: https://github.com/hestiacp/hestiacp/issues/2804

**Closed as completed by istiak101** 2023-07-26 01:13 UTC
Labels: bug
