### ISSUE TITLE
[FEATURE] Try first to Validate Let's Encrypt with their staging environment before trying to issue a certificate

### ISSUE THREAD

**Issue by jlguerrerosanz** [hestiacp/hestiacp#1820] opened 2021-05-19 20:06 UTC
In their webpage LE  highly recommends to try to create the certificates first against their staging environment.
https://letsencrypt.org/docs/staging-environment/

**To reduce the ocurrence of error 429 - rate limit reached**
Hestia could first try and if no error code is returned, then try to issue the certificate.

**Comment by jaapmarcus** [comment] 2021-05-19 20:26
Hestia has all ready support for the Staging Environment. Add LE_STAGING='yes'  to /usr/local/hestia/conf/hestia.conf

If we are going to implement it we have rewrite parts of if as Staging is current not compatible with the live version as Lets encrypt "user account" are always saved on the current location

> We highly recommend testing against our staging environment before using our production environment. This will allow you to get things right before issuing trusted certificates and reduce the chance of your running up against rate limits.

Officially any web site added on production system.  

I hope the changes to 1.4 will solve most of the issues the issues there are currently are with LE.

**Comment by jlguerrerosanz** [comment] 2021-05-19 22:21
Thank you @jaapmarcus for your answer.

My server just got **banned for 7 days** for migrating from a Plesk server. **The limit is 10 domains per IP per 3 hours.** I couldn't imagine that the limit was so low.

In this cases, it is interesting to minimize the LE load. 

I believe that this would be low priority but since we already talked about parsing the LE error logs and checking nginx before trying, in my igonrance I thought that it would be easy to implement.

**Comment by ScIT-Raphael** [comment] 2021-05-20 01:13
As Jaap already pointed out, this is currently not possible to implement with a whole rewrite of the letsencrypt user handling. Also it would massively increase (double it) the certificate generation time, due to this reasons, I'm going to close this feature request.

**Closed as completed by ScIT-Raphael** 2021-05-20 01:13 UTC

**Comment by jaapmarcus** [comment] 2021-05-20 08:06
> My server just got **banned for 7 days** for migrating from a Plesk server. **The limit is 10 domains per IP per 3 hours.** I couldn't imagine that the limit was so low.

There are multiple limits:

> The main limit is Certificates per Registered Domain (50 per week). A registered domain is, generally speaking, the part of the domain you purchased from your domain name registrar. For instance, in the name www.example.com, the registered domain is example.com. In new.blog.example.co.uk, the registered domain is example.co.uk. We use the Public Suffix List to calculate the registered domain. Exceeding the Certificates Per Registered Domain limit is reported with the error message too many certificates already issued, possibly with additional details.

50 Certificates / week / domain (domain.tld) is counted as an domain. But also domain.tld.uk for UK / Australia and so on

Not a solution for the staging limit

> 100 Names per Certificate

Same here

> Duplicate Certificate limit of 5 per week.

You can request up to 5 times a week for a renewal of the same domain. So far I have seen 1 time hit this limit it was caused by an bug in a Template that went unnoticed.

> There is a Failed Validation limit of 5 failures per account, per hostname, per hour. 

This issue happens more often it can be caused by the following reason:
1. Nginx / Apache2 not restarting
2. Use of Cloudflare with force SSL enabled 
3. DNS pointing to the wrong server
4. IPv6
5. Issues with templates and so on... 
6. Proxy template disabled

----

1. Should be solved and users will get notified that the restart fails. 
2. Hard to solve unless we build in CF support into Hestia
3. Hard to solve when a user uses CF DNS doesn't point to your server
4. Will be fixed in a future release
5. See 1. When enabling an template and config test fails Hestia will trow a error
6. Disabled via GUI as there is no reason to use it without.  

> You can create a maximum of 10 Accounts per IP Address per 3 hours

This limit will not solve the usage via Staging "Site"

10 accounts per 3 hours you can request up to 100 domains per account how ever Hestia doesn't support yet the creation for "Multiple Hestia users" per "LE account" as LE Accounts are currently tied to the Hestia User. 

500 Accounts per IP range (Ip v6/48)
Same as above:

> ACME v2 API you can create a maximum of 300 New Orders per account per 3 hours

Same as above if you request to Many domains you will still reach this limit. 

> 300 Pending Authorizations 

Same as here 

See https://letsencrypt.org/docs/rate-limits/

I hope this clarifies it a a bit
